/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.NGOAdmin;

import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.CardLayout;

import Business.UserAccount.UserAccount;
import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrgNGO;
import Business.Organization.Organization;
import Business.WorkQueue.NGOFundRequest;
import Business.WorkQueue.WorkRequest;
import UI.HealthcareOfficer.MapJPanel;


/**
 *
 * @author MALLESH
 */
public class NGOAdminWAJPanel extends javax.swing.JPanel {
private JPanel userContainer;
private UserAccount userAccount;
private AdminOrgNGO ngoAdminOrg;
private Enterprise enterprise;

    /**
     * Creates new form NGOAdministratorWorkAreaPanel
     */
    public NGOAdminWAJPanel(JPanel userContainer, UserAccount userAccount, Organization organization, Enterprise enterprise) {
    initComponents();  
    this.userContainer = userContainer;
    this.userAccount = userAccount;
    this.ngoAdminOrg = (AdminOrgNGO) organization;
    this.enterprise = enterprise;
    populateRequestTable();
    }
    public void populateRequestTable() {

    DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
    model.setRowCount(0);

    for (WorkRequest request : ngoAdminOrg.getWorkQueue().getWorkRequests()) {

        Object[] row = new Object[5];

        row[0] = (NGOFundRequest) request;
        row[1] = request.getRequestSender().getEmployee().getEmployeeName();

        if (request.getRequestStatus().equalsIgnoreCase("Sent to Director")) {
            row[2] = null;
        } else {
            row[2] = request.getRequestReceiver() == null
                    ? null
                    : request.getRequestReceiver().getEmployee().getEmployeeName();
        }

        row[3] = request.getRequestStatus();
        row[4] = ((NGOFundRequest) request).getRequestedFundAmount();

        model.addRow(row);
    }

    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    workRequestJTable.setRowSorter(sorter);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJBtn = new javax.swing.JButton();
        processRequestJBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));

        workRequestJTable.setBackground(new java.awt.Color(204, 204, 204));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Location", "Sender", "Receiver", "Status", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        assignJBtn.setBackground(new java.awt.Color(102, 255, 153));
        assignJBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        assignJBtn.setText("Assign To Me");
        assignJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJBtnActionPerformed(evt);
            }
        });

        processRequestJBtn.setBackground(new java.awt.Color(255, 102, 102));
        processRequestJBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        processRequestJBtn.setText("Process Request");
        processRequestJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processRequestJBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NGO Admin Panel");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ngo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(assignJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(processRequestJBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(processRequestJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assignJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJBtnActionPerformed
        // TODO add your handling code here:
    int selectedRow = workRequestJTable.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null, "Please select a row!");
        return;
    }

    NGOFundRequest request = (NGOFundRequest) workRequestJTable.getValueAt(selectedRow, 0);

    if (request.getRequestStatus().equals("Sent")) {

        request.setRequestReceiver(userAccount);
        request.setRequestStatus("Pending on " + userAccount.getEmployee().getEmployeeName());

        populateRequestTable();
        JOptionPane.showMessageDialog(null, "Request assigned to you!");

    } else {
        JOptionPane.showMessageDialog(
                null,
                "Cannot assign. Status: " + request.getRequestStatus(),
                "Warning",
                JOptionPane.WARNING_MESSAGE
        );
    }
    }//GEN-LAST:event_assignJBtnActionPerformed

    private void processRequestJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processRequestJBtnActionPerformed
        
     // TODO add your handling code here:
     int selectedRow = workRequestJTable.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null, "Select a row first!");
        return;
    }

    NGOFundRequest request = (NGOFundRequest) workRequestJTable.getValueAt(selectedRow, 0);

    if (request.getRequestStatus().equalsIgnoreCase("Rejected")) {
        JOptionPane.showMessageDialog(null, "Cannot process a rejected request!");
        return;
    }

    if (request.getRequestStatus().equalsIgnoreCase("Sent to Director")) {
        JOptionPane.showMessageDialog(null, "Already processed!");
        return;
    }

    if (request.getRequestStatus().equalsIgnoreCase("Sent")) {
        JOptionPane.showMessageDialog(null, "Assign the request first!");
        return;
    }

    if (!userAccount.equals(request.getRequestReceiver())) {
        JOptionPane.showMessageDialog(null, "Not Authorized!");
        return;
    }

    NGOAdminProcessWRJPanel processPanel =
            new NGOAdminProcessWRJPanel(userContainer, userAccount, request, enterprise);

    userContainer.add("NGOAdminProcessWRJPanel", processPanel);

    CardLayout layout = (CardLayout) userContainer.getLayout();
    layout.next(userContainer);
    }//GEN-LAST:event_processRequestJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processRequestJBtn;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables

}
