/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.BloodBankManager;

import Business.Ecosystem;
import Business.Organization.BloodBankManagerOrg;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientTreatmentWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author gaganaananda
 * 
 */
public class BloodBankManagerDashboardJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    private Ecosystem ecosystem;
    private UserAccount userAccount;
    private BloodBankManagerOrg bloodBankManagerOrg;



    /**
     * Creates new form BloodBankDashboardJPanel
     */
    public BloodBankManagerDashboardJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Ecosystem business) {
        initComponents();
        
        this.jPanel = userProcessContainer;
        this.userAccount = account;
        this.ecosystem = business;
        this.bloodBankManagerOrg = (BloodBankManagerOrg) organization;

        populateTable();

        
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTableWorkReq.getModel();

        model.setRowCount(0);
        
        
        for (WorkRequest request : bloodBankManagerOrg.getWorkQueue().getWorkRequests()) {

            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getRequestSender().getEmployee().getEmployeeName();
            row[2] = ((PatientTreatmentWorkRequest) request).getBloodBankOfficer();
            row[3] = request.getRequestStatus();
            row[4] = ((PatientTreatmentWorkRequest ) request).getPatientInfo().getPatientFirstName() + " " + ((PatientTreatmentWorkRequest) request).getPatientInfo().getPatientLastName();
            row[5] = ((PatientTreatmentWorkRequest) request).getPatientInfo().getPatientId();
            row[6]=((PatientTreatmentWorkRequest) request).getRequiredBloodUnits();
            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTableWorkReq.setRowSorter(sorter);
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableWorkReq = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(null);

        jTableWorkReq.setBackground(new java.awt.Color(204, 204, 204));
        jTableWorkReq.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableWorkReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Patient Name", "Patient Id", "Blood Units"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableWorkReq);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 940, 90);

        btnAssign.setBackground(new java.awt.Color(255, 102, 102));
        btnAssign.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAssign.setText("Assign to me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign);
        btnAssign.setBounds(190, 130, 140, 40);

        btnProcess.setBackground(new java.awt.Color(255, 102, 102));
        btnProcess.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess);
        btnProcess.setBounds(370, 130, 140, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blood bank request.gif"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(100, 190, 630, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        int selectedRow = jTableWorkReq.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please select a row first");
            return;
        }

        PatientTreatmentWorkRequest request = (PatientTreatmentWorkRequest) jTableWorkReq.getValueAt(selectedRow, 0);
        if (request.getBloodBankOfficer() == null) {
            if (request.getRequestStatus().equalsIgnoreCase("SentToBloodBank")) {
                request.setBloodBankOfficer(userAccount);
                request.setRequestStatus("Pending on Blood Bank");
                //  request.setReceiver(userAccount);
                populateTable();
                JOptionPane.showMessageDialog(null, "The request is assigned to You!");
            } else {
                JOptionPane.showMessageDialog(null, "Cannot assign this lab request as the current status is: " + request.getRequestStatus());
            }
        }
        else
        {

            if(userAccount.equals(request.getLabTechnician()))

            {
                JOptionPane.showMessageDialog(null,"Request is already assigned to you");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Request is assigned to other Lab Assistant");
            }
        }

        
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed

       int selectedRow = jTableWorkReq.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

        PatientTreatmentWorkRequest request = (PatientTreatmentWorkRequest) jTableWorkReq.getValueAt(selectedRow, 0);

        BloodRequestProcessingJPanel processWorkRequestJPanel = new BloodRequestProcessingJPanel(jPanel, request);
        if (request.getBloodBankOfficer() != null) {
            if (userAccount.equals(request.getBloodBankOfficer())) {
                if (request.getRequestStatus().equalsIgnoreCase("Pending on Blood Bank")) {

                    jPanel.add("processWorkRequestJPanel", processWorkRequestJPanel);
                    CardLayout layout = (CardLayout) jPanel.getLayout();
                    layout.next(jPanel);
                } else {
                    JOptionPane.showMessageDialog(null, "Cannot process the request as the status is: " + request.getRequestStatus());
                }

            } else {

                JOptionPane.showMessageDialog(null, "Not authorised to process the request");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please assign the request first");
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableWorkReq;
    // End of variables declaration//GEN-END:variables
}
