/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.BloodBankManager;

import Business.WorkQueue.PatientTreatmentWorkRequest;
import UI.Patient.PatientWAJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import UI.BloodBankManager.BloodBankManagerDashboardJPanel;




/**
 *
 * @author gaganaananda
 */
public class BloodRequestProcessingJPanel extends javax.swing.JPanel {

    JPanel jPanel;
    PatientTreatmentWorkRequest patientTreatmentWorkRequest;

    /**
     * Creates new form BloodRequestProcessingJPanel
     */
    public BloodRequestProcessingJPanel(JPanel userProcessContainer, PatientTreatmentWorkRequest patientTreatmentWorkRequest) {
        initComponents();
        
        this.jPanel = userProcessContainer;
        this.patientTreatmentWorkRequest = patientTreatmentWorkRequest;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sbmtJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rsltMsgJTextField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(null);

        sbmtJButton.setBackground(new java.awt.Color(255, 102, 102));
        sbmtJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sbmtJButton.setText("Submit Result");
        sbmtJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtJButtonActionPerformed(evt);
            }
        });
        add(sbmtJButton);
        sbmtJButton.setBounds(420, 120, 117, 36);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Message");
        add(jLabel1);
        jLabel1.setBounds(330, 90, 60, 17);
        add(rsltMsgJTextField);
        rsltMsgJTextField.setBounds(410, 80, 160, 30);

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnBack.setText(" >>Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 20, 110, 27);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Blood Bank");
        add(jLabel2);
        jLabel2.setBounds(250, 30, 195, 29);

        jLabel3.setBackground(new java.awt.Color(0, 153, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab test results.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(-110, 10, 730, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

      jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BloodBankManagerDashboardJPanel dwjp = (BloodBankManagerDashboardJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void sbmtJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtJButtonActionPerformed
       
String bloodBankMessage = rsltMsgJTextField.getText().trim();
        if (bloodBankMessage.equals("")) {
            JOptionPane.showMessageDialog(null, "Result is mandatory");
            return;
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                patientTreatmentWorkRequest.setBloodBankNotes(bloodBankMessage);
                patientTreatmentWorkRequest.setRequestStatus("Blood Bank Request Completed");
                JOptionPane.showMessageDialog(null, "Result submitted successfully");
                rsltMsgJTextField.setText("");
                sbmtJButton.setEnabled(false);
            }

        }

    }//GEN-LAST:event_sbmtJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField rsltMsgJTextField;
    private javax.swing.JButton sbmtJButton;
    // End of variables declaration//GEN-END:variables

}
