/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.BloodBankManager;




/**
 *
 * @author gaganaananda
 */
public class BloodRequestProcessingJPanel extends javax.swing.JPanel {

 

    /**
     * Creates new form BloodRequestProcessingJPanel
     */
    public BloodRequestProcessingJPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sbmtJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rsltMsgJTextField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(null);

        sbmtJButton.setBackground(new java.awt.Color(255, 102, 102));
        sbmtJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sbmtJButton.setText("Submit Result");
        sbmtJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtJButtonActionPerformed(evt);
            }
        });
        add(sbmtJButton);
        sbmtJButton.setBounds(420, 120, 117, 36);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Message");
        add(jLabel1);
        jLabel1.setBounds(330, 90, 60, 17);
        add(rsltMsgJTextField);
        rsltMsgJTextField.setBounds(410, 80, 160, 30);

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnBack.setText(" >>Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 20, 110, 27);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Blood Bank");
        add(jLabel2);
        jLabel2.setBounds(250, 30, 195, 29);

        jLabel3.setBackground(new java.awt.Color(0, 153, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab test results.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(-110, 10, 730, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

      
    }//GEN-LAST:event_btnBackActionPerformed

    private void sbmtJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtJButtonActionPerformed
       


    }//GEN-LAST:event_sbmtJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField rsltMsgJTextField;
    private javax.swing.JButton sbmtJButton;
    // End of variables declaration//GEN-END:variables

}
