/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Doctor;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AccountantOrg;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AccountantBillingRequest;
import Business.WorkQueue.PatientTreatmentWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author gaganaananda 
 */
public class BillingRequestJPanel extends javax.swing.JPanel {

 private JPanel jPanel;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private PatientTreatmentWorkRequest patientTreatmentWorkRequest;
    private Ecosystem ecosystem;
    private double consultationCharge = 50;

    /**
     * Creates new form BillingRequestJPanel
     */
    public BillingRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, PatientTreatmentWorkRequest workRequest) {
        initComponents();
        
        
        this.jPanel = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.patientTreatmentWorkRequest = workRequest;
        populateTable();
        
    }
    
    
    public void populateTable() {
        txtFirstname.setText(patientTreatmentWorkRequest.getPatientInfo().getPatientFirstName());
        txtLastname.setText(patientTreatmentWorkRequest.getPatientInfo().getPatientLastName());
        txtPatientID.setText(String.valueOf(patientTreatmentWorkRequest.getPatientInfo().getPatientId()));
        txtAssignDoc.setText(patientTreatmentWorkRequest.getAssignedDoctor().getEmployee().getEmployeeName());
        txtConsulCharge.setText(String.valueOf(consultationCharge));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAssignDoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtConsulCharge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        medChrgTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtLabCharge = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        miscChrgTxt = new javax.swing.JTextField();
        btnSendBillReq = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Billing Request Form");
        add(jLabel1);
        jLabel1.setBounds(310, 60, 230, 29);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("PATIENT INFORMATION");
        add(jLabel6);
        jLabel6.setBounds(290, 220, 180, 17);

        txtFirstname.setEditable(false);
        add(txtFirstname);
        txtFirstname.setBounds(220, 250, 131, 23);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("First Name :");
        add(jLabel7);
        jLabel7.setBounds(130, 260, 90, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Last Name :");
        add(jLabel10);
        jLabel10.setBounds(390, 260, 74, 17);

        txtLastname.setEditable(false);
        add(txtLastname);
        txtLastname.setBounds(470, 260, 131, 23);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Assigned Doctor :");
        add(jLabel8);
        jLabel8.setBounds(110, 290, 107, 17);

        txtAssignDoc.setEditable(false);
        add(txtAssignDoc);
        txtAssignDoc.setBounds(220, 290, 130, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Patient Id:");
        add(jLabel2);
        jLabel2.setBounds(390, 290, 66, 17);

        txtPatientID.setEditable(false);
        add(txtPatientID);
        txtPatientID.setBounds(470, 290, 131, 23);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("BILLING INFORMATION");
        add(jLabel3);
        jLabel3.setBounds(300, 360, 165, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Consultaion Charges (USD) :");
        add(jLabel4);
        jLabel4.setBounds(230, 390, 177, 21);

        txtConsulCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsulChargeActionPerformed(evt);
            }
        });
        add(txtConsulCharge);
        txtConsulCharge.setBounds(410, 390, 82, 23);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Medication Charges (USD):");
        add(jLabel5);
        jLabel5.setBounds(240, 460, 168, 21);
        add(medChrgTxt);
        medChrgTxt.setBounds(410, 460, 82, 23);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Lab Test Charges (USD) :");
        add(jLabel11);
        jLabel11.setBounds(240, 420, 157, 21);

        txtLabCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLabChargeActionPerformed(evt);
            }
        });
        add(txtLabCharge);
        txtLabCharge.setBounds(410, 420, 82, 23);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Miscellaneous Charges (USD):");
        add(jLabel12);
        jLabel12.setBounds(220, 490, 183, 17);
        add(miscChrgTxt);
        miscChrgTxt.setBounds(410, 490, 82, 23);

        btnSendBillReq.setBackground(new java.awt.Color(255, 102, 102));
        btnSendBillReq.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSendBillReq.setText("Send Billing Request");
        btnSendBillReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendBillReqActionPerformed(evt);
            }
        });
        add(btnSendBillReq);
        btnSendBillReq.setBounds(300, 540, 137, 32);

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText(">>Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(80, 40, 76, 23);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doctor bill.gif"))); // NOI18N
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel9);
        jLabel9.setBounds(-10, -10, 1470, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLabChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLabChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLabChargeActionPerformed

    private void txtConsulChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsulChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsulChargeActionPerformed

    private void btnSendBillReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendBillReqActionPerformed
        
        String consulCharge = txtConsulCharge.getText().trim();
        String labChargesStr = txtLabCharge.getText();
        String miscellaneouschargesStr = miscChrgTxt.getText();
        String medicationChargesStr = medChrgTxt.getText();
        if (consulCharge.equals("") || labChargesStr.equals("") || miscellaneouschargesStr.equals("") || medicationChargesStr.equals("")) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
        } else {
            
            try {
                Double.parseDouble(consulCharge);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please provide a Numeric value for Consultation Charges");
                return;
            }
            
            try {
                Integer.parseInt(labChargesStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type a Numeric value for Lab Charges");
                return;
            }
            try {
                Integer.parseInt(miscellaneouschargesStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type a Numeric value for Miscellaneous charges");
                return;
            }
            try {
                Integer.parseInt(medicationChargesStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type numeric value for Medication charges");
                return;
            }
            double labCharges = Double.parseDouble(labChargesStr);
            double miscellaneouscharges = Double.parseDouble(miscellaneouschargesStr);
            double medicationCharges = Double.parseDouble(medicationChargesStr);
            double billingAmount = labCharges + consultationCharge + medicationCharges + miscellaneouscharges;

            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                patientTreatmentWorkRequest.setRequestStatus("Consultation Completed");

                AccountantBillingRequest accountantBillingRequest = new AccountantBillingRequest();
                accountantBillingRequest.setTotalBillAmount(billingAmount);
                //  accountantBillingRequest.setPatientId(Integer.parseInt(txtPatientId.getText()));

                accountantBillingRequest.setRequestSender(userAccount);
                accountantBillingRequest.setRequestStatus("Sent");

                accountantBillingRequest.setPatientRecord(patientTreatmentWorkRequest.getPatientInfo());

                Organization org = null;
                for (Organization organization : enterprise.getOrgDir().getOrganizations()) {

                    if (organization instanceof AccountantOrg) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {

                    org.getWorkQueue().getWorkRequests().add(accountantBillingRequest);
                    userAccount.getWorkQueue().getWorkRequests().add(accountantBillingRequest);

                }

                JOptionPane.showMessageDialog(null, "Billing request submitted successfully");
                btnSendBillReq.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnSendBillReqActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);                           
       
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendBillReq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField medChrgTxt;
    private javax.swing.JTextField miscChrgTxt;
    private javax.swing.JTextField txtAssignDoc;
    private javax.swing.JTextField txtConsulCharge;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLabCharge;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtPatientID;
    // End of variables declaration//GEN-END:variables

}
