/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Doctor;

import Business.Enterprise.Enterprise;
import Business.Organization.BloodBankManagerOrg;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientTreatmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gaganaananda
 */
public class BloodBankManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BloodBankManagerJPanel
     */
    
    private JPanel jPanel;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientTreatmentWorkRequest patientTreatmentWorkRequest;
    
    public BloodBankManagerJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, PatientTreatmentWorkRequest patientTreatmentWorkRequest) {
        initComponents();
      
        
        this.jPanel = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.patientTreatmentWorkRequest = patientTreatmentWorkRequest;
        txtValue.setText(enterprise.getName());
        btnRequest.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLabMessage = new javax.swing.JTextField();
        txtLabType = new javax.swing.JTextField();
        btnRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setText(">>Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        title.setText("Blood Bank Request");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 170, 30));

        jLabel2.setText("Enterprise: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        txtValue.setText("<value>");
        add(txtValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel4.setText("Message");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel5.setText("Unit of Blood");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));
        add(txtLabMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 150, -1));

        txtLabType.addActionListener(this::txtLabTypeActionPerformed);
        add(txtLabType, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 150, -1));

        btnRequest.setBackground(new java.awt.Color(255, 102, 102));
        btnRequest.setText("Request Button");
        btnRequest.addActionListener(this::btnRequestActionPerformed);
        add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtLabTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLabTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLabTypeActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:

  String  bloodUnits = txtLabType.getText().trim();            
            try {
                Integer.parseInt(bloodUnits);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please provide numeric values in Blood Units textfield");
                return;
            }
            
        
        String message = txtLabMessage.getText().trim();

        if (bloodUnits.equals("")) {
            JOptionPane.showMessageDialog(null, "Blood Units is mandatory!");
            return;
        }
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory");
            return;
        }

        
        patientTreatmentWorkRequest.setBloodBankNotes(message);
        patientTreatmentWorkRequest.setRequestSender(userAccount);
        patientTreatmentWorkRequest.setRequestStatus("SentToBloodBank");
        patientTreatmentWorkRequest.setRequestReceiver(null);
        patientTreatmentWorkRequest.setRequiredBloodUnits(Integer.valueOf(bloodUnits));
        


        Organization org = null;

        for (Organization organization : enterprise.getOrgDir().getOrganizations()) {

            if (organization instanceof BloodBankManagerOrg) {
                org = organization;
                break;
            }
        }
        if (org != null) {

            org.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
            userAccount.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);


            JOptionPane.showMessageDialog(null, "Blood Bank request sent");
            txtLabMessage.setText("");
            txtLabType.setText("");
            btnRequest.setEnabled(false);
        }

    }//GEN-LAST:event_btnRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtLabMessage;
    private javax.swing.JTextField txtLabType;
    private javax.swing.JLabel txtValue;
    // End of variables declaration//GEN-END:variables

}
