/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Administrative;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author gaganaananda
 */
public class OrganizationManagementJPanel extends javax.swing.JPanel {
    private OrganizationDirectory orgdir;
    private JPanel jPanel;
    private Enterprise enterpz;

    /**
     * Creates new form OrganizationManagementJPanel
     */
    public OrganizationManagementJPanel(JPanel userProcessContainer, OrganizationDirectory directory, Enterprise enterprise) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.orgdir = directory;
        this.enterpz = enterprise;

        pplTbl();
        pplCmbx();
    }
    private void pplCmbx() {
        jComboBoxOrg.removeAllItems();
        for (Organization.Type orgType : enterpz.getAllOrganizationTypes()) {
            jComboBoxOrg.addItem(orgType);
        }
    }
    
    private void pplTbl() {
        DefaultTableModel model = (DefaultTableModel) jTableOrg.getModel();

        model.setRowCount(0);

        for (Organization organization : orgdir.getOrganizations()) {
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationId();
            row[1] = organization;

            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTableOrg.setRowSorter(sorter);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrg = new javax.swing.JTable();
        jComboBoxOrg = new javax.swing.JComboBox();
        lblOrg = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        btnDeleteOrg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));

        jTableOrg.setBackground(new java.awt.Color(204, 204, 204));
        jTableOrg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTableOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organization Id", "Organization Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableOrg);
        if (jTableOrg.getColumnModel().getColumnCount() > 0) {
            jTableOrg.getColumnModel().getColumn(0).setResizable(false);
            jTableOrg.getColumnModel().getColumn(1).setResizable(false);
        }

        jComboBoxOrg.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxOrg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBoxOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblOrg.setBackground(new java.awt.Color(204, 204, 204));
        lblOrg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOrg.setText("Organization Type ");

        backJButton.setBackground(new java.awt.Color(255, 102, 102));
        backJButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("Manage Organizations");

        btnDeleteOrg.setBackground(new java.awt.Color(255, 102, 102));
        btnDeleteOrg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDeleteOrg.setText("Delete");
        btnDeleteOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrgActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage_org-2.gif"))); // NOI18N

        btnAdd.setBackground(new java.awt.Color(255, 102, 102));
        btnAdd.setText("Add Organization");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)
                        .addGap(116, 116, 116)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblOrg)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(btnDeleteOrg))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrg))
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Organization.Type type = (Organization.Type) jComboBoxOrg.getSelectedItem();
        // populateTable();
        ArrayList<String> orgName = new ArrayList<String>();
        DefaultTableModel model = (DefaultTableModel) jTableOrg.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            orgName.add(model.getValueAt(i, 1).toString());
        }

        if (orgName.contains(type.getValue())) {
            JOptionPane.showMessageDialog(null, "Organization already exists!! ");
            return;
        } else {
            orgdir.createOrganization(type);
        }

        pplTbl();
        
    }//GEN-LAST:event_btnAddActionPerformed


    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel.remove(this);
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }
    
    private void btnDeleteOrgActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
       int selectedRow = jTableOrg.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details", "Warning!",
                    JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Organization organization = (Organization) jTableOrg.getValueAt(selectedRow, 1);

            enterpz.getOrgDir().getOrganizations().remove(organization);
            pplTbl();

        }

    }

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleteOrg;
    private javax.swing.JComboBox jComboBoxOrg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOrg;
    private javax.swing.JLabel lblOrg;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
