/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Administrative;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PatientOrg;
import Business.Role.Doctor;
import Business.Role.Roles;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author malleshm
 */
public class UserAccountManagementJPanel extends javax.swing.JPanel {
    /**
     * Creates new form UserAccountManagementJPanel
     */
        public JPanel jPanel;
    //private Enterprise enterpz;
    public Enterprise enterprise; 
    public UserAccountManagementJPanel(JPanel container, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        this.jPanel = container;
        

        popOrgCmbx();
        popData();

    }
  public void popOrgCmbx() {
        organizationJComboBox.removeAllItems();
 
 
        for (Organization organization : enterprise.getOrgDir().getOrganizations()) {
 
            if (!(organization instanceof PatientOrg)) {
                organizationJComboBox.addItem(organization);
            }
        }
    }
 
    public void pplEmpCmbx(Organization organization) {
        employeeJComboBox.removeAllItems();
 
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {
            employeeJComboBox.addItem(employee);
        }
    }
 
    private void popRoleCmbx(Organization organization) {
        roleJComboBox.removeAllItems();
        for (Roles role : organization.getSupportedRole()) {
            roleJComboBox.addItem(role);
        }
        doctorType();
    }
 
    public void popData() {
 
        DefaultTableModel model = (DefaultTableModel) jTableUser.getModel();
 
        model.setRowCount(0);
 
 
        for (Organization organization : enterprise.getOrgDir().getOrganizations()) {
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
 
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getUserRole();
                ((DefaultTableModel) jTableUser.getModel()).addRow(row);
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJBtn = new javax.swing.JButton();
        createUserJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        OrganizationJLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passwordjLabel = new javax.swing.JLabel();
        doctorTypeJComboBox1 = new javax.swing.JComboBox<>();
        organizationJComboBox = new javax.swing.JComboBox<>();
        employeeJComboBox = new javax.swing.JComboBox<>();
        roleJComboBox = new javax.swing.JComboBox<>();
        nameJTextField = new javax.swing.JTextField();
        reenterPasswordjLbl = new javax.swing.JLabel();
        passwordJTextField = new javax.swing.JPasswordField();
        rePasswordJTextField = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJBtn.setText("Back");
        backJBtn.addActionListener(this::backJBtnActionPerformed);
        add(backJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        createUserJButton.setText("Create");
        createUserJButton.addActionListener(this::createUserJButtonActionPerformed);
        add(createUserJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, -1, -1));

        jLabel1.setText("Manage User Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User Name", "Role"
            }
        ));
        jScrollPane1.setViewportView(jTableUser);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 620, 230));

        jLabel2.setText("Doctor Type");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        OrganizationJLbl.setText("Organization");
        add(OrganizationJLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel4.setText("Employee");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, 20));

        jLabel5.setText("Role");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jLabel6.setText("User Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        passwordjLabel.setText("Password");
        add(passwordjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        doctorTypeJComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiologist", "Physician", "Neurologist", "Pediatrician", "Orthopedic" }));
        doctorTypeJComboBox1.addActionListener(this::doctorTypeJComboBox1ActionPerformed);
        add(doctorTypeJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 160, -1));

        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel<Organization>());
        organizationJComboBox.addActionListener(this::organizationJComboBoxActionPerformed);
        add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 160, -1));

        employeeJComboBox.setModel(new javax.swing.DefaultComboBoxModel<Employee>());
        employeeJComboBox.addActionListener(this::employeeJComboBoxActionPerformed);
        add(employeeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 160, -1));

        roleJComboBox.setModel(new javax.swing.DefaultComboBoxModel<Roles>());
        roleJComboBox.addActionListener(this::roleJComboBoxActionPerformed);
        add(roleJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 160, -1));

        nameJTextField.addActionListener(this::nameJTextFieldActionPerformed);
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 160, -1));

        reenterPasswordjLbl.setText("re-enter Password");
        add(reenterPasswordjLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));
        add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 160, -1));
        add(rePasswordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserJButtonActionPerformed
        // TODO add your handling code here:
             String userName = nameJTextField.getText();
       String password = String.valueOf(passwordJTextField.getPassword());
       String rePassword = String.valueOf(rePasswordJTextField.getPassword());

        Organization organization = (Organization) organizationJComboBox.getSelectedItem();
        Employee employee = (Employee) employeeJComboBox.getSelectedItem();
        Roles role = (Roles) roleJComboBox.getSelectedItem();
        String doctorType = "";
        if (role instanceof Doctor) {
            doctorType = (String) doctorTypeJComboBox1.getSelectedItem();
 
        }
        if (userName == null || userName.equals("")) {
            nameJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Username cannot be empty");
            return;
        }
 
        if (password == null || password.equals("")) {
            nameJTextField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            passwordJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Password cannot be empty");
            return;
        }
 
        if (!passwordPatternCorrect()) {
            JOptionPane.showMessageDialog(null, "Password should be at least 6 Characters "
                    + "digits and a combination of number , uppercase letter, "
                    + "lowercase letter and Special characters are not allowed other than $, +, _");
            passwordJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            return;
        }
 
        if (!password.equals(rePassword)) {
            JOptionPane.showMessageDialog(null, "Passwords don't match");
            passwordJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            rePasswordJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            return;
        } else {
 
            List<UserAccount> userAccountList = organization.getUserAccountDirectory().getUserAccountList();
            for (UserAccount userAccount : userAccountList) {
                if (userAccount.getUsername().equals(userName)) {
                    JOptionPane.showMessageDialog(null, "username already taken!!");
                    nameJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
                    return;
                }
            }
            if (role instanceof Doctor){
 
                organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role,
                        doctorType);
            } else {
                organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
            }
            popData();
            nameJTextField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            passwordJTextField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            rePasswordJTextField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            passwordJTextField.setText("");
            rePasswordJTextField.setText("");
            nameJTextField.setText("");
        }
    }
    private boolean passwordPatternCorrect() {
        Pattern p = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[$+_])(?=\\S+$).{6,}$");
        Matcher m = p.matcher(String.valueOf(passwordJTextField.getPassword()));
        boolean b = m.matches();
        return b;
    }//GEN-LAST:event_createUserJButtonActionPerformed

    private void doctorTypeJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorTypeJComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorTypeJComboBox1ActionPerformed

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void roleJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleJComboBoxActionPerformed

    private void employeeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeJComboBoxActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:
        Organization organization = (Organization) organizationJComboBox.getSelectedItem();
        if (organization != null) {
            pplEmpCmbx(organization);
            popRoleCmbx(organization);
        }
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        jPanel.remove(this);
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);

    }//GEN-LAST:event_backJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OrganizationJLbl;
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton createUserJButton;
    private javax.swing.JComboBox<String> doctorTypeJComboBox1;
    private javax.swing.JComboBox<Employee> employeeJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUser;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox<Organization> organizationJComboBox;
    private javax.swing.JPasswordField passwordJTextField;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JPasswordField rePasswordJTextField;
    private javax.swing.JLabel reenterPasswordjLbl;
    private javax.swing.JComboBox<Roles> roleJComboBox;
    // End of variables declaration//GEN-END:variables

    private void doctorType() {
         Roles role = (Roles) roleJComboBox.getSelectedItem();
        if (role instanceof Doctor) {
            doctorTypeJComboBox1.setEnabled(true);
            doctorTypeJComboBox1.setVisible(true);
            jLabel2.setVisible(true);
        } else {
            doctorTypeJComboBox1.setEnabled(false);
            doctorTypeJComboBox1.setVisible(false);
            jLabel2.setVisible(false);
        }

    }
    
}
