/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GovernmentTreasurer;

import Business.Enterprise.Enterprise;
import Business.Organization.TreasurerOrg;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.GovernmentFundRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jayan
 */
public class TreasurerWorkRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private GovernmentFundRequest request;
    private UserAccount account;
    private TreasurerOrg organization;
    private Enterprise enterprise;

    /**
     * Creates new form TreasurerWorkRequestJPanel
     */
    public TreasurerWorkRequestJPanel(JPanel userProcessContainer, GovernmentFundRequest request, UserAccount account, TreasurerOrg organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        
        // Populate fields with request data
        fieldAmount.setText(String.valueOf(request.getRequiredFunding()));
        fieldLocation.setText(request.getRegionName());
        fieldPopulation.setText(String.valueOf(request.getPatientCount()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDisburseAmount = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        fieldMessage = new javax.swing.JTextField();
        lblLocation = new javax.swing.JLabel();
        fieldLocation = new javax.swing.JTextField();
        fieldPopulation = new javax.swing.JTextField();
        lblPopulation = new javax.swing.JLabel();
        fieldAmount = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));

        btnDisburseAmount.setBackground(new java.awt.Color(255, 102, 102));
        btnDisburseAmount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDisburseAmount.setText("Disburse Amount");
        btnDisburseAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisburseAmountActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnReject.setBackground(new java.awt.Color(255, 102, 102));
        btnReject.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMessage.setText("Message");

        fieldMessage.setBackground(new java.awt.Color(204, 204, 204));

        lblLocation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLocation.setText("Location");

        fieldLocation.setBackground(new java.awt.Color(204, 204, 204));
        fieldLocation.setEnabled(false);

        fieldPopulation.setBackground(new java.awt.Color(204, 204, 204));
        fieldPopulation.setEnabled(false);

        lblPopulation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPopulation.setText("Population");

        fieldAmount.setBackground(new java.awt.Color(204, 204, 204));
        fieldAmount.setEnabled(false);

        lblAmount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAmount.setText("Amount");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Treasurer Work Area");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Treasurer work area.gif"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAmount)
                                    .addComponent(lblLocation)
                                    .addComponent(lblPopulation)
                                    .addComponent(lblMessage))
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDisburseAmount)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(142, 142, 142)
                        .addComponent(lblTitle)))
                .addGap(40, 40, 40)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocation)
                            .addComponent(fieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPopulation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMessage))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDisburseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisburseAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisburseAmountActionPerformed
        btnDisburseAmount.setEnabled(true);
        String message = fieldMessage.getText();
        
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        }
        
        request.setRequestNote(message);
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
        
        if (dialogResult == JOptionPane.YES_OPTION) {
            request.setRequestStatus("Accepted");
            JOptionPane.showMessageDialog(null, "Funds Disbursed Successfully!");
            btnDisburseAmount.setEnabled(false);
            fieldMessage.setText("");
            btnReject.setEnabled(false);
        }
        fieldMessage.setText("");

    }//GEN-LAST:event_btnDisburseAmountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        TreasurerWorkAreaJPanel treasurerWorkAreaJPanel = (TreasurerWorkAreaJPanel) component;
        treasurerWorkAreaJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
     
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        String message = fieldMessage.getText();
        
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        }
        
        request.setRequestNote(message);
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
        
        if (dialogResult == JOptionPane.YES_OPTION) {
            request.setRequestStatus("Rejected");
            fieldMessage.setText("");
            btnReject.setEnabled(false);
            btnDisburseAmount.setEnabled(false);
        }
        fieldMessage.setText("");
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDisburseAmount;
    private javax.swing.JButton btnReject;
    private javax.swing.JTextField fieldAmount;
    private javax.swing.JTextField fieldLocation;
    private javax.swing.JTextField fieldMessage;
    private javax.swing.JTextField fieldPopulation;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPopulation;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
