/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.InsuranceAgent;

import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceEnterprise;
import Business.Insurance.Insurance;
import Business.UserAccount.UserAccount;
import Business.CustomerInsurance.CustomerInsurance;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author jayan
 */
public class AddNewPolicyHolderJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private InsuranceEnterprise enterprise;
    private String policyNumber;
    
    /**
     * Creates new form CreateNewUserJPanel
     */
    public AddNewPolicyHolderJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, String policyNumber) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = (InsuranceEnterprise) enterprise;
        this.account = account;
        this.policyNumber = policyNumber;
        
        
        populateFields();
        populateTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPolicyNumber = new javax.swing.JLabel();
        fieldPolicyNumber = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        fieldSSN = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        fieldAddress = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblInsurancePolicyName = new javax.swing.JLabel();
        comboBoxInsurancePolicyName = new javax.swing.JComboBox();
        btnAddCustomer = new javax.swing.JButton();
        lblSubTitle = new javax.swing.JLabel();
        lblInsuranceInfo = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        lblInsuranceCoverage = new javax.swing.JLabel();
        fieldInsuranceCoverage = new javax.swing.JTextField();
        comboBoxGender = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        lblAllCustomers = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        fieldDOB = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 204));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 51));
        lblTitle.setText("Add New Customer");

        lblPolicyNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPolicyNumber.setForeground(new java.awt.Color(0, 51, 51));
        lblPolicyNumber.setText("Policy Number ");

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(0, 51, 51));
        lblFirstName.setText("First Name");

        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(0, 51, 51));
        lblLastName.setText("Last Name");

        lblSSN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(0, 51, 51));
        lblSSN.setText("SSN");

        lblDOB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(0, 51, 51));
        lblDOB.setText("Date of birth");

        lblGender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGender.setForeground(new java.awt.Color(0, 51, 51));
        lblGender.setText("Gender");

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(0, 51, 51));
        lblAddress.setText("Address");

        lblInsurancePolicyName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInsurancePolicyName.setForeground(new java.awt.Color(0, 51, 51));
        lblInsurancePolicyName.setText("Insurance Policy Name");

        comboBoxInsurancePolicyName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboBoxInsurancePolicyNameFocusGained(evt);
            }
        });
        comboBoxInsurancePolicyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxInsurancePolicyNameActionPerformed(evt);
            }
        });

        btnAddCustomer.setBackground(new java.awt.Color(255, 102, 102));
        btnAddCustomer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        lblSubTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(0, 51, 51));
        lblSubTitle.setText("Personal Information");

        lblInsuranceInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblInsuranceInfo.setForeground(new java.awt.Color(0, 51, 51));
        lblInsuranceInfo.setText("Insurance  Information");

        lblPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(0, 51, 51));
        lblPhone.setText("Phone");

        lblInsuranceCoverage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInsuranceCoverage.setForeground(new java.awt.Color(0, 51, 51));
        lblInsuranceCoverage.setText("Insurance Coverage %");

        comboBoxGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male", "Other" }));

        tblCustomers.setBackground(new java.awt.Color(204, 204, 204));
        tblCustomers.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer Name", "Policy Number", "Policy Name", "Coverage %"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomers);

        lblAllCustomers.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAllCustomers.setForeground(new java.awt.Color(255, 255, 255));
        lblAllCustomers.setText("All Customers");

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient details.gif"))); // NOI18N

        fieldDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDOBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDOB)
                            .addComponent(lblSSN)
                            .addComponent(lblAddress)
                            .addComponent(lblFirstName))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblGender)
                                    .addComponent(lblPhone)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fieldSSN, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fieldDOB, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(28, 28, 28)
                                            .addComponent(lblLastName))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldLastName)
                                    .addComponent(fieldPhone)
                                    .addComponent(comboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblPolicyNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lblInsurancePolicyName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboBoxInsurancePolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblInsuranceCoverage)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 550, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(lblSubTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(114, 114, 114)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAllCustomers))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(lblInsuranceInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle))
                .addGap(18, 18, 18)
                .addComponent(lblSubTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolicyNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFirstName)
                        .addComponent(lblLastName)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGender))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblDOB))
                    .addComponent(fieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(fieldAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInsuranceInfo)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInsurancePolicyName)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBoxInsurancePolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsuranceCoverage))
                .addGap(18, 18, 18)
                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lblAllCustomers)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(373, 373, 373))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed

        if (fieldFirstName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide first name");
            return;
        }
        if (fieldLastName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide last name");
            return;
        }
        if (fieldDOB.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide Date of birth in MM-dd-yyyy format");
            return;
        }
        if (comboBoxGender.getItemCount() == 0) {
            JOptionPane.showMessageDialog(null, "Please provide Gender");
            return;
        }
        if (fieldSSN.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide SSN");
            return;
        }
        if (fieldPhone.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide phone");
            return;
        }
        if (fieldAddress.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide address");
            return;
        }
        if (fieldInsuranceCoverage.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide Insurance Coverage");
            return;
        } else {
            String firstName = fieldFirstName.getText().trim();
            String lastName = fieldLastName.getText().trim();
            String dateOfBirth = fieldDOB.getText().trim();
            
            String gender = comboBoxGender.getSelectedItem().toString();
            String ssn = fieldSSN.getText().trim();
            if (!validateSSN()) {
                JOptionPane.showMessageDialog(null, "Invalid SSN format!\n\nUnited States Social Security numbers must be in format AAA-GG-SSSS with following rules:\n"
                        + "- The first three digits (area number) cannot be 000, 666, or between 900-999\n"
                        + "- Digits four and five (group number) must be between 01-99\n"
                        + "- The last four digits (serial numbers) must be between 0001-9999");
                fieldSSN.setBorder(BorderFactory.createLineBorder(Color.RED));
                return;
            }
            if (validateSSN()) {
                fieldSSN.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            }
            String address = fieldAddress.getText().trim();
            String phone = fieldPhone.getText().trim();
            if (!validatePhone()) {
                JOptionPane.showMessageDialog(null, "Invalid phone number format!\n\nValid formats:\n"
                        + "- 1234567890\n"
                        + "- 123-456-7890\n"
                        + "- (123)4567890\n"
                        + "- (123)456-7890");
                fieldPhone.setBorder(BorderFactory.createLineBorder(Color.RED));
                return;
            }
            if (validatePhone()) {
                fieldPhone.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            }
            String policyNum = fieldPolicyNumber.getText().trim();
            String insurancePolicyName = comboBoxInsurancePolicyName.getSelectedItem().toString();
            double coverage = Double.parseDouble(fieldInsuranceCoverage.getText().trim());
            try {
                Double.parseDouble(fieldInsuranceCoverage.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please provide numeric values in coverage textfield");
                return;
            }
            Insurance insurance = new Insurance(insurancePolicyName, enterprise.getName(), coverage);
            CustomerInsurance customer = new CustomerInsurance(insurance, policyNum);
            customer.setCustomerFirstName(firstName);
            customer.setCustomerLastName(lastName);
            customer.setDateOfBirth(dateOfBirth);
            customer.setGender(gender);
            customer.setSSN(ssn);
            customer.setPhoneNumber(phone);
            customer.setAddress(address);
            customer.setInsurance(insurance);
            enterprise.getcustInsDir().getInsuranceCustomers().add(customer);
            enterprise.getcustInsDir().getInsuranceCustomers();
            populateTable();
            resetFields();
            JOptionPane.showMessageDialog(null, "Customer has been added successfully!");
        }

            
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void comboBoxInsurancePolicyNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboBoxInsurancePolicyNameFocusGained
       System.out.println("Gained");
    }//GEN-LAST:event_comboBoxInsurancePolicyNameFocusGained

    private void comboBoxInsurancePolicyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxInsurancePolicyNameActionPerformed
        Insurance selectedPolicy = (Insurance) comboBoxInsurancePolicyName.getSelectedItem();
        fieldInsuranceCoverage.setText(String.valueOf(selectedPolicy.getCoverage()));
    }//GEN-LAST:event_comboBoxInsurancePolicyNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void fieldDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDOBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboBoxGender;
    private javax.swing.JComboBox comboBoxInsurancePolicyName;
    private javax.swing.JTextField fieldAddress;
    private javax.swing.JTextField fieldDOB;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldInsuranceCoverage;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldPolicyNumber;
    private javax.swing.JTextField fieldSSN;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAllCustomers;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblInsuranceCoverage;
    private javax.swing.JLabel lblInsuranceInfo;
    private javax.swing.JLabel lblInsurancePolicyName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPolicyNumber;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCustomers;
    // End of variables declaration//GEN-END:variables

   private boolean validatePhone() {
        Pattern pattern = Pattern.compile("\\d{10}|(?:\\d{3}-){2}\\d{4}|\\(\\d{3}\\)\\d{3}-?\\d{4}");
        Matcher matcher = pattern.matcher(fieldPhone.getText());
        return matcher.matches();
    }
    
    private boolean validateSSN() {
        Pattern pattern = Pattern.compile("^(?!000|666)[0-8][0-9]{2}-(?!00)[0-9]{2}-(?!0000)[0-9]{4}$");
        Matcher matcher = pattern.matcher(fieldSSN.getText());
        return matcher.matches();
    }
    
    private void resetFields() {
        fieldPolicyNumber.setText(UUID.randomUUID().toString().substring(0, 7));
        fieldFirstName.setText("");
        fieldLastName.setText("");
        fieldPhone.setText("");
        fieldSSN.setText("");
        fieldDOB.setText("");
        fieldAddress.setText("");
    }
    
    private void populateFields() {
        fieldPolicyNumber.setText(policyNumber);
        List<Insurance> policies = enterprise.getInsPlcyDir().getPolicies();
        for (Insurance policy : policies) {
            comboBoxInsurancePolicyName.addItem(policy);
        }
        Insurance selectedPolicy = (Insurance) comboBoxInsurancePolicyName.getSelectedItem();
        
        if (selectedPolicy != null) {
            fieldInsuranceCoverage.setText(String.valueOf(selectedPolicy.getCoverage()));
        } else {
            JOptionPane.showMessageDialog(null, "No Existing policy!");
            return;
        }
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCustomers.getModel();
        model.setRowCount(0);
        List<CustomerInsurance> customers = enterprise.getcustInsDir().getInsuranceCustomers();
        for (CustomerInsurance customer : customers) {
            Object[] row = new Object[4];
            row[0] = customer.getCustomerFirstName() + " " + customer.getCustomerLastName();
            row[1] = customer;
            row[2] = customer.getInsurance().getPolicyName();
            row[3] = customer.getInsurance().getCoverage();
            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblCustomers.setRowSorter(sorter);
    }
}
