/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.InsuranceAgent;

import Business.Enterprise.Enterprise;
import Business.Organization.InsuranceFinanceOrg;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InsuranceWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author jayan
 */

public class ProcessRequestJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private InsuranceWorkRequest request;
    
    /**
     * Creates new form ProcessRequestJPanel
     */
    public ProcessRequestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, InsuranceWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.request = request;
        this.account = account;
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPolicyNumber = new javax.swing.JLabel();
        fieldPolicyNumber = new javax.swing.JTextField();
        lblClaimAmount = new javax.swing.JLabel();
        fieldClaimAmount = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        fieldMessage = new javax.swing.JTextField();
        btnAcceptAndSendRequest = new javax.swing.JButton();
        btnRejectRequest = new javax.swing.JButton();
        lblCustomerName = new javax.swing.JLabel();
        fieldCustomerName = new javax.swing.JTextField();
        lblTotalBillAmount = new javax.swing.JLabel();
        fieldTotalBillAmount = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(null);

        lblPolicyNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPolicyNumber.setText("Policy Number");
        add(lblPolicyNumber);
        lblPolicyNumber.setBounds(199, 98, 90, 15);

        fieldPolicyNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fieldPolicyNumber.setEnabled(false);
        add(fieldPolicyNumber);
        fieldPolicyNumber.setBounds(307, 96, 145, 20);

        lblClaimAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblClaimAmount.setText("Claim Amount");
        add(lblClaimAmount);
        lblClaimAmount.setBounds(204, 212, 86, 15);

        fieldClaimAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fieldClaimAmount.setEnabled(false);
        add(fieldClaimAmount);
        fieldClaimAmount.setBounds(308, 210, 144, 20);

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMessage.setText("Message");
        add(lblMessage);
        lblMessage.setBounds(239, 250, 52, 15);

        fieldMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMessageActionPerformed(evt);
            }
        });
        add(fieldMessage);
        fieldMessage.setBounds(309, 248, 265, 23);

        btnAcceptAndSendRequest.setBackground(new java.awt.Color(255, 102, 102));
        btnAcceptAndSendRequest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAcceptAndSendRequest.setText("Accept and Send Request To Finance Department");
        btnAcceptAndSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptAndSendRequestActionPerformed(evt);
            }
        });
        add(btnAcceptAndSendRequest);
        btnAcceptAndSendRequest.setBounds(121, 286, 309, 34);

        btnRejectRequest.setBackground(new java.awt.Color(255, 102, 102));
        btnRejectRequest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRejectRequest.setText("Reject Request");
        btnRejectRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectRequestActionPerformed(evt);
            }
        });
        add(btnRejectRequest);
        btnRejectRequest.setBounds(455, 286, 117, 34);

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCustomerName.setText("Customer Name");
        add(lblCustomerName);
        lblCustomerName.setBounds(192, 136, 96, 15);

        fieldCustomerName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fieldCustomerName.setEnabled(false);
        add(fieldCustomerName);
        fieldCustomerName.setBounds(306, 134, 146, 20);

        lblTotalBillAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalBillAmount.setText("Total Bill Amount");
        add(lblTotalBillAmount);
        lblTotalBillAmount.setBounds(185, 174, 106, 15);

        fieldTotalBillAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fieldTotalBillAmount.setEnabled(false);
        add(fieldTotalBillAmount);
        fieldTotalBillAmount.setBounds(308, 172, 144, 20);

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 11, 78, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insurance agent.jpg"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(220, -50, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMessageActionPerformed

    private void btnAcceptAndSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptAndSendRequestActionPerformed
        String message = fieldMessage.getText();
        if (message.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide a message!");
            return;
        } else {
            request.setRequestNote(message);
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to approve and send this request to the Finance Department?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                Organization org = null;
                for (Organization organization : enterprise.getOrgDir().getOrganizations()) {
                    if (organization instanceof InsuranceFinanceOrg) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {
                    org.getWorkQueue().getWorkRequests().add(request);
                    account.getWorkQueue().getWorkRequests().add(request);
                }
                JOptionPane.showMessageDialog(null, "Request has been approved and sent to the Finance Department successfully!");
                request.setRequestStatus("Sent To Finance Department");
                request.setInsuranceAgent(account.getEmployee().getEmployeeName());
                request.setRequestReceiver(null);
                fieldMessage.setText("");
                btnRejectRequest.setEnabled(false);
                btnAcceptAndSendRequest.setEnabled(false);
            }
            fieldMessage.setText("");
        }
    }//GEN-LAST:event_btnAcceptAndSendRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AllInsuranceRequestsJPanel allInsuranceRequestsJPanel = (AllInsuranceRequestsJPanel) component;
        allInsuranceRequestsJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRejectRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectRequestActionPerformed
        String message = fieldMessage.getText();
        if (message.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide a reason for rejection!");
            return;
        } else {
            request.setRequestNote(message);
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to reject this request?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                request.setRequestStatus("Rejected");
                request.setRequestNote(fieldMessage.getText().trim());
                request.setInsuranceAgent(account.getEmployee().getEmployeeName());
                fieldMessage.setText("");
                btnRejectRequest.setEnabled(false);
                btnAcceptAndSendRequest.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Request has been rejected successfully!");
            }
            fieldMessage.setText("");
        }
    }//GEN-LAST:event_btnRejectRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptAndSendRequest;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRejectRequest;
    private javax.swing.JTextField fieldClaimAmount;
    private javax.swing.JTextField fieldCustomerName;
    private javax.swing.JTextField fieldMessage;
    private javax.swing.JTextField fieldPolicyNumber;
    private javax.swing.JTextField fieldTotalBillAmount;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblClaimAmount;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPolicyNumber;
    private javax.swing.JLabel lblTotalBillAmount;
    // End of variables declaration//GEN-END:variables
    
    private void populateFields() {
        fieldPolicyNumber.setText(request.getPolicyNumber());
        fieldCustomerName.setText(request.getInsuredPatient().getCustomerFirstName() + " " + request.getInsuredPatient().getCustomerLastName());
        fieldTotalBillAmount.setText(String.valueOf(request.getTreatmentBill()));
        fieldClaimAmount.setText(String.valueOf(request.getClaimAmount()));
    }
}
