/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.LabAssistant;
import Business.Ecosystem;
import Business.Organization.LabOrg;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientTreatmentWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author MALLESH
 */
public class LabAssistantWAJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Ecosystem business;
    private UserAccount userAccount;
    private LabOrg labOrganization;


    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public LabAssistantWAJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.labOrganization = (LabOrg) organization;

        populateLabRequestTable();
    }
    
    public void populateLabRequestTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTbl.getModel();
        model.setRowCount(0);

        for (WorkRequest request : labOrganization.getWorkQueue().getWorkRequests()) {
            PatientTreatmentWorkRequest ptwr = (PatientTreatmentWorkRequest) request;

            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getRequestSender().getEmployee().getEmployeeName();
            row[2] = ptwr.getLabTechnician();
            row[3] = request.getRequestStatus();
            row[4] = ptwr.getPatientInfo().getPatientFirstName() + " " + ptwr.getPatientInfo().getPatientLastName();
            row[5] = ptwr.getPatientInfo().getPatientId();
            row[6] = request.getDiagnosticType();

            model.addRow(row);
        }

        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        workRequestJTbl.setRowSorter(sorter);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTbl = new javax.swing.JTable();
        assignToMeJBtn = new javax.swing.JButton();
        processJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BloodTestJBtn = new javax.swing.JButton();
        mriScanJBtn = new javax.swing.JButton();
        xRayJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(null);

        workRequestJTbl.setBackground(new java.awt.Color(204, 204, 204));
        workRequestJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Patient Name", "Patient Id", "Test Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 730, 90);

        assignToMeJBtn.setBackground(new java.awt.Color(0, 153, 255));
        assignToMeJBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        assignToMeJBtn.setText("Assign to me");
        assignToMeJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeJBtnActionPerformed(evt);
            }
        });
        add(assignToMeJBtn);
        assignToMeJBtn.setBounds(10, 130, 140, 40);

        processJBtn.setBackground(new java.awt.Color(0, 153, 255));
        processJBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        processJBtn.setText("Process");
        processJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJBtnActionPerformed(evt);
            }
        });
        add(processJBtn);
        processJBtn.setBounds(600, 130, 140, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/scanner.gif"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(10, 180, 710, 370);

        BloodTestJBtn.setBackground(new java.awt.Color(0, 153, 255));
        BloodTestJBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BloodTestJBtn.setText("Blood Test");
        BloodTestJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodTestJBtnActionPerformed(evt);
            }
        });
        add(BloodTestJBtn);
        BloodTestJBtn.setBounds(150, 130, 140, 40);

        mriScanJBtn.setBackground(new java.awt.Color(0, 153, 255));
        mriScanJBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mriScanJBtn.setText("MRI scan");
        mriScanJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mriScanJBtnActionPerformed(evt);
            }
        });
        add(mriScanJBtn);
        mriScanJBtn.setBounds(450, 130, 140, 40);

        xRayJBtn.setBackground(new java.awt.Color(0, 153, 255));
        xRayJBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        xRayJBtn.setText("X Ray");
        xRayJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xRayJBtnActionPerformed(evt);
            }
        });
        add(xRayJBtn);
        xRayJBtn.setBounds(290, 130, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab test request.gif"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(741, 200, 580, 360);
    }// </editor-fold>//GEN-END:initComponents

    private void assignToMeJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeJBtnActionPerformed
    int selectedRow = workRequestJTbl.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null,"Please select a row first");
        return;
    }

    PatientTreatmentWorkRequest request =
            (PatientTreatmentWorkRequest) workRequestJTbl.getValueAt(selectedRow, 0);

    // If no lab technician assigned yet
    if (request.getLabTechnician() == null) {

        if (request.getRequestStatus().equalsIgnoreCase("SentToLab")) {

            request.setLabTechnician(userAccount);
            request.setRequestStatus("Pending on Lab Technician");

            populateLabTable();
            JOptionPane.showMessageDialog(null, "The request is now assigned to you!");

        } else {
            JOptionPane.showMessageDialog(null,
                "Cannot assign because status is: " + request.getRequestStatus());
        }
    }
    else {
        if (userAccount.equals(request.getLabTechnician())) {
            JOptionPane.showMessageDialog(null,"Request is already assigned to you");
        } else {
            JOptionPane.showMessageDialog(null,"Request is assigned to another Lab Technician");
        }
    }

    }//GEN-LAST:event_assignToMeJBtnActionPerformed

    private void processJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJBtnActionPerformed
    int selectedRow = workRequestJTbl.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null, "Please select a row");
        return;
    }

    PatientTreatmentWorkRequest request =
            (PatientTreatmentWorkRequest) workRequestJTbl.getValueAt(selectedRow, 0);

    // Only assigned technician can process
    if (request.getLabTechnician() != null) {

        if (userAccount.equals(request.getLabTechnician())) {

            if (request.getRequestStatus().equalsIgnoreCase("Pending on Lab Technician")) {

                LabProcessWRJPanel processPanel =
                        new LabProcessWRJPanel (userProcessContainer, request);

                userProcessContainer.add("processPanel", processPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);

            } else {
                JOptionPane.showMessageDialog(null,
                        "Cannot process because status is: " + request.getRequestStatus());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Not authorized to process this request");
        }

    } else {
        JOptionPane.showMessageDialog(null, "Please assign the request first");
    }
    }//GEN-LAST:event_processJBtnActionPerformed

    private void BloodTestJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodTestJBtnActionPerformed
    // TODO add your handling code here:
    int selectedRow = workRequestJTbl.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null,"Please select a row first");
        return;
    }

    PatientTreatmentWorkRequest request =
            (PatientTreatmentWorkRequest) workRequestJTbl.getValueAt(selectedRow, 0);

    if (userAccount.equals(request.getLabTechnician())) {

        if (request.getRequestStatus().equalsIgnoreCase("Pending on Lab Technician")) {
            request.setDiagnosticType("Blood Test");
        } else {
            JOptionPane.showMessageDialog(null, "Test is already done!");
        }

    } else {
        JOptionPane.showMessageDialog(null,
                "Lab technician is not assigned, cannot modify test type");
    }

    }//GEN-LAST:event_BloodTestJBtnActionPerformed

    private void mriScanJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mriScanJBtnActionPerformed
    // TODO add your handling code here
    int selectedRow = workRequestJTbl.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null,"Please select a row first");
        return;
    }

    PatientTreatmentWorkRequest request =
            (PatientTreatmentWorkRequest) workRequestJTbl.getValueAt(selectedRow, 0);

    if (userAccount.equals(request.getLabTechnician())) {

        if (request.getRequestStatus().equalsIgnoreCase("Pending on Lab Technician")) {
            request.setDiagnosticType("MRI Scan");
        } else {
            JOptionPane.showMessageDialog(null, "Test is already done!");
        }

    } else {
        JOptionPane.showMessageDialog(null,
                "Lab technician is not assigned, cannot modify test type");
    }
    }//GEN-LAST:event_mriScanJBtnActionPerformed

    private void xRayJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xRayJBtnActionPerformed
        // TODO add your handling code here:
    int selectedRow = workRequestJTbl.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null,"Please select a row first");
        return;
    }

    PatientTreatmentWorkRequest request =
            (PatientTreatmentWorkRequest) workRequestJTbl.getValueAt(selectedRow, 0);

    if (userAccount.equals(request.getLabTechnician())) {

        if (request.getRequestStatus().equalsIgnoreCase("Pending on Lab Technician")) {
            request.setDiagnosticType("X Ray");
        } else {
            JOptionPane.showMessageDialog(null, "Test is already done!");
        }

    } else {
        JOptionPane.showMessageDialog(null,
                "Lab technician is not assigned, cannot modify test type");
    }

    }//GEN-LAST:event_xRayJBtnActionPerformed
    
    private void populateLabTable() {

    DefaultTableModel model = (DefaultTableModel) workRequestJTbl.getModel();
    model.setRowCount(0);

    for (WorkRequest req : labOrganization.getWorkQueue().getWorkRequests()) {

        PatientTreatmentWorkRequest request = (PatientTreatmentWorkRequest) req;

        Object[] row = new Object[7];
        row[0] = request;
        row[1] = request.getRequestSender().getEmployee().getEmployeeName();
        row[2] = request.getLabTechnician();
        row[3] = request.getRequestStatus();
        row[4] = request.getPatientInfo().getPatientFirstName() + " " +
                 request.getPatientInfo().getPatientLastName();
        row[5] = request.getPatientInfo().getPatientId();
        row[6] = request.getDiagnosticType();

        model.addRow(row);
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BloodTestJBtn;
    private javax.swing.JButton assignToMeJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mriScanJBtn;
    private javax.swing.JButton processJBtn;
    private javax.swing.JTable workRequestJTbl;
    private javax.swing.JButton xRayJBtn;
    // End of variables declaration//GEN-END:variables
}
