
package UI.HealthcareOfficer;

import Business.Ecosystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author jayan
 */
public class MapJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Ecosystem ecosystem;
     
    /**
     * Creates new form MapJPanel
     */
    public MapJPanel(JPanel userProcessContainer, UserAccount account, Ecosystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecosystem = ecosystem;
        setupMapDisplay();
    }
    
    // New Constructor added by MALLESH
    public MapJPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        setupMapDisplay();
    }
    
    private void setupMapDisplay() {
        // Create custom panel with map visualization
        JPanel mapPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                // Draw a simple map representation
                g.setColor(new Color(200, 230, 255));
                g.fillRect(0, 0, getWidth(), getHeight());
                
                // Draw grid lines
                g.setColor(new Color(180, 180, 180));
                for (int i = 0; i < getWidth(); i += 50) {
                    g.drawLine(i, 0, i, getHeight());
                }
                for (int i = 0; i < getHeight(); i += 50) {
                    g.drawLine(0, i, getWidth(), i);
                }
                
                // Draw location marker for Boston
                g.setColor(Color.RED);
                int centerX = getWidth() / 2;
                int centerY = getHeight() / 2;
                g.fillOval(centerX - 10, centerY - 10, 20, 20);
                
                // Draw location label
                g.setColor(Color.BLACK);
                g.setFont(new Font("Arial", Font.BOLD, 14));
                g.drawString("Boston, MA", centerX + 15, centerY);
                g.drawString("(Northeastern University Area)", centerX + 15, centerY + 15);
                
                // Draw coordinates
                g.setFont(new Font("Arial", Font.PLAIN, 12));
                g.drawString("Latitude: 42.3398°N", 10, 20);
                g.drawString("Longitude: 71.0892°W", 10, 35);
            }
        };
        
        // Add the custom map panel to jXMapViewer container
        jXMapViewer.setLayout(new java.awt.BorderLayout());
        jXMapViewer.removeAll();
        jXMapViewer.add(mapPanel, java.awt.BorderLayout.CENTER);
        jXMapViewer.revalidate();
        jXMapViewer.repaint();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXMapViewer = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();

        jXMapViewer.setBackground(new java.awt.Color(0, 153, 204));
        jXMapViewer.setMaximumSize(new java.awt.Dimension(783, 554));
        jXMapViewer.setMinimumSize(new java.awt.Dimension(783, 554));
        jXMapViewer.setPreferredSize(new java.awt.Dimension(783, 554));

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXMapViewerLayout = new javax.swing.GroupLayout(jXMapViewer);
        jXMapViewer.setLayout(jXMapViewerLayout);
        jXMapViewerLayout.setHorizontalGroup(
            jXMapViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXMapViewerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack)
                .addContainerGap(895, Short.MAX_VALUE))
        );
        jXMapViewerLayout.setVerticalGroup(
            jXMapViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXMapViewerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(600, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXMapViewer, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXMapViewer, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel jXMapViewer;
    // End of variables declaration//GEN-END:variables
}
