/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HealthcareOfficer;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.SecretaryOrg;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.GovernmentFundRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author jayan
 */
public class OfficerProcessRequestJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount account;
    private GovernmentFundRequest request;
    
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public OfficerProcessRequestJPanel(JPanel userProcessContainer, UserAccount account, GovernmentFundRequest request, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.request = request;
        
        // Populate fields with request data
        fieldAmount.setText(String.valueOf(request.getRequiredFunding()));
        fieldLocation.setText(request.getRegionName());
        fieldPopulation.setText(String.valueOf(request.getPatientCount()));
    }

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldAmount = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        fieldMessage = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnSendRequestToApprove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblLocation = new javax.swing.JLabel();
        fieldLocation = new javax.swing.JTextField();
        fieldPopulation = new javax.swing.JTextField();
        lblPopulation = new javax.swing.JLabel();
        Reject = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));

        fieldAmount.setBackground(new java.awt.Color(204, 204, 204));
        fieldAmount.setEnabled(false);

        lblAmount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAmount.setText("Amount");

        lblMessage.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMessage.setText("Message");

        fieldMessage.setBackground(new java.awt.Color(204, 204, 204));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Officer Request Process area ");

        btnSendRequestToApprove.setBackground(new java.awt.Color(255, 102, 102));
        btnSendRequestToApprove.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSendRequestToApprove.setText("Send Request to Secretary to approve");
        btnSendRequestToApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestToApproveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblLocation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLocation.setText("Location");

        fieldLocation.setBackground(new java.awt.Color(204, 204, 204));
        fieldLocation.setEnabled(false);

        fieldPopulation.setBackground(new java.awt.Color(204, 204, 204));
        fieldPopulation.setEnabled(false);

        lblPopulation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPopulation.setText("Population");

        Reject.setBackground(new java.awt.Color(255, 102, 102));
        Reject.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Reject.setText("Reject");
        Reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/networks.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblLocation, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblMessage)
                                        .addComponent(lblPopulation))
                                    .addGap(38, 38, 38)
                                    .addComponent(fieldPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(fieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTitle)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Reject, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSendRequestToApprove))))
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLocation)
                    .addComponent(fieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPopulation))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMessage))
                .addGap(49, 49, 49)
                .addComponent(btnSendRequestToApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Reject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSendRequestToApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestToApproveActionPerformed
        // TODO add your handling code here:

        String message = fieldMessage.getText();
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        } else {
            request.setRequestNote(message);
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                request.setRequestSender(account);
                request.setRequestStatus("Sent to Secretary");
                
                Organization org = null;
                for (Organization organization : enterprise.getOrgDir().getOrganizations()) {
                    if (organization instanceof SecretaryOrg) {
                        org = organization;
                        break;
                    }
                }
                
                if (org != null) {
                    org.getWorkQueue().getWorkRequests().add(request);
                    account.getWorkQueue().getWorkRequests().add(request);
                }
                
                JOptionPane.showMessageDialog(null, "Request to Secretary Successful!!!");
                fieldMessage.setText("");
                Reject.setEnabled(false);
                btnSendRequestToApprove.setEnabled(false);
            }
            fieldMessage.setText("");
        }

    }//GEN-LAST:event_btnSendRequestToApproveActionPerformed

    private void RejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectActionPerformed
        String message = fieldMessage.getText();
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        } else {
            request.setRequestNote(message);
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                request.setRequestStatus("Rejected");
                fieldMessage.setText("");
                Reject.setEnabled(false);
                btnSendRequestToApprove.setEnabled(false);
            }
            fieldMessage.setText("");
        }
    }//GEN-LAST:event_RejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reject;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendRequestToApprove;
    private javax.swing.JTextField fieldAmount;
    private javax.swing.JTextField fieldLocation;
    private javax.swing.JTextField fieldMessage;
    private javax.swing.JTextField fieldPopulation;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPopulation;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
