/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.NGODirector;
import Business.Enterprise.Enterprise;
import Business.Organization.DirectorOrgNGO;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NGOFundRequest;
import Business.WorkQueue.WorkRequest;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author MALLESH
 */
public class NGODirectorWAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TreasurerWorkAreaJPanel
     */
    private JPanel containerPanel;
    private UserAccount directorAccount;
    private DirectorOrgNGO directorOrg;
    private Enterprise enterpriseRef;
    public NGODirectorWAJPanel(JPanel containerPanel, UserAccount userAccount, Organization organization, Enterprise enterpriseRef) {
        initComponents();
        this.containerPanel = containerPanel;
        this.directorAccount = userAccount;
        this.directorOrg = (DirectorOrgNGO) organization;
        this.enterpriseRef = enterpriseRef;

        populateDirectorRequestTable();
    }
    public void populateDirectorRequestTable() {

        DefaultTableModel model = (DefaultTableModel) dirctorWorkReqestJTbl.getModel();
        model.setRowCount(0);

        for (WorkRequest request : directorOrg.getWorkQueue().getWorkRequests()) {

            NGOFundRequest fundReq = (NGOFundRequest) request;

            Object[] row = new Object[6];
            row[0] = request.getRequestSender().getEmployee().getEmployeeName();
            row[1] = (request.getRequestReceiver() == null)
                    ? "Unassigned"
                    : request.getRequestReceiver().getEmployee().getEmployeeName();
            row[2] = request.getRequestStatus();
            row[3] = fundReq.getRequestedFundAmount();
            row[4] = fundReq.getRequestNote();
            row[5] = request;  // store request object

            model.addRow(row);
        }

        dirctorWorkReqestJTbl.setRowSorter(new TableRowSorter<>(model));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dirctorWorkReqestJTbl = new javax.swing.JTable();
        assignToMeBtn = new javax.swing.JButton();
        processRequestBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Director Work Area ");

        dirctorWorkReqestJTbl.setBackground(new java.awt.Color(204, 204, 204));
        dirctorWorkReqestJTbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dirctorWorkReqestJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Status", "Amount", "Message", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dirctorWorkReqestJTbl);

        assignToMeBtn.setBackground(new java.awt.Color(102, 255, 153));
        assignToMeBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        assignToMeBtn.setText("Assign To Me");
        assignToMeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeBtnActionPerformed(evt);
            }
        });

        processRequestBtn.setBackground(new java.awt.Color(255, 102, 102));
        processRequestBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        processRequestBtn.setText("Process Request");
        processRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processRequestBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage user - 2.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(assignToMeBtn)
                        .addGap(77, 77, 77)
                        .addComponent(processRequestBtn)
                        .addGap(212, 212, 212)))
                .addContainerGap(557, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignToMeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignToMeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeBtnActionPerformed
        int selectedRow = dirctorWorkReqestJTbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request first.");
            return;
        }

        NGOFundRequest request = (NGOFundRequest) dirctorWorkReqestJTbl.getValueAt(selectedRow, 5);

        if (!request.getRequestStatus().equals("Sent to Director")) {
            JOptionPane.showMessageDialog(null,
                    "This request cannot be assigned.\nCurrent status: " + request.getRequestStatus());
            return;
        }

        request.setRequestReceiver(directorAccount);
        request.setRequestStatus("Pending on " + directorAccount.getEmployee().getEmployeeName());

        JOptionPane.showMessageDialog(null, "Request assigned to you");
        populateDirectorRequestTable();

    }//GEN-LAST:event_assignToMeBtnActionPerformed

    private void processRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processRequestBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = dirctorWorkReqestJTbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request first.");
            return;
        }

        NGOFundRequest request = (NGOFundRequest) dirctorWorkReqestJTbl.getValueAt(selectedRow, 5);

        if (request.getRequestStatus().equals("Sent to Director")) {
            JOptionPane.showMessageDialog(null, "Assign the request before processing.");
            return;
        }

        if (request.getRequestStatus().equals("Approved by Director")) {
            JOptionPane.showMessageDialog(null, "Request already processed.");
            return;
        }

        if (request.getRequestStatus().equals("Rejected")) {
            JOptionPane.showMessageDialog(null, "Cannot process a rejected request.");
            return;
        }

        if (!directorAccount.equals(request.getRequestReceiver())) {
            JOptionPane.showMessageDialog(null, "This request is not assigned to you.");
            return;
        }

        // Navigate to processing panel
        NGODirectorProcessWRJPanel processPanel = new NGODirectorProcessWRJPanel(containerPanel, request);

        containerPanel.add("DirectorProcessRequestJPanel", processPanel);
        ((CardLayout) containerPanel.getLayout()).next(containerPanel);

    }//GEN-LAST:event_processRequestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeBtn;
    private javax.swing.JTable dirctorWorkReqestJTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processRequestBtn;
    // End of variables declaration//GEN-END:variables
}
