/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.NGODirector;

import Business.Enterprise.Enterprise;
import Business.Organization.DirectorOrgNGO;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NGOFundRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author MALLESH
 */
public class NGODirectorWAJPanel extends javax.swing.JPanel {

    
    private JPanel containerPanel;
    private UserAccount directorAccount;
    private DirectorOrgNGO directorOrg;
    private Enterprise enterpriseRef;
    /**
     * Creates new form TreasurerWorkAreaJPanel
     */

        public NGODirectorWAJPanel(JPanel containerPanel, UserAccount directorAccount, DirectorOrgNGO directorOrg, Enterprise enterpriseRef) {
        initComponents();
        this.containerPanel = containerPanel;
        this.directorAccount = directorAccount;
        this.directorOrg = directorOrg;
        this.enterpriseRef = enterpriseRef;

        populateDirectorTable(); // load table
    }
        public void populateDirectorTable() {
        DefaultTableModel model = (DefaultTableModel) directorWorkRequestJTable.getModel();
        model.setRowCount(0);

        for (WorkRequest request : directorOrg.getWorkQueue().getWorkRequests()) {

            Object[] row = new Object[6];

            row[0] = request.getRequestSender().getEmployee().getEmployeeName();
            row[1] = request.getRequestReceiver() == null
                    ? "Not Assigned"
                    : request.getRequestReceiver().getEmployee().getEmployeeName();

            row[2] = request.getRequestStatus();
            row[3] = ((NGOFundRequest) request).getRequestedFundAmount();
            row[4] = request.getRequestNote();
            row[5] = request; // IMPORTANT for processing

            model.addRow(row);
        }

        directorWorkRequestJTable.setRowSorter(new TableRowSorter<>(model));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        directorWorkRequestJTable = new javax.swing.JTable();
        assignToMeJBtn = new javax.swing.JButton();
        processRequestJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Director Work Area ");

        directorWorkRequestJTable.setBackground(new java.awt.Color(204, 204, 204));
        directorWorkRequestJTable.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        directorWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Status", "Amount", "Message", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(directorWorkRequestJTable);

        assignToMeJBtn.setBackground(new java.awt.Color(102, 255, 153));
        assignToMeJBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        assignToMeJBtn.setText("Assign To Me");
        assignToMeJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeJBtnActionPerformed(evt);
            }
        });

        processRequestJBtn.setBackground(new java.awt.Color(255, 102, 102));
        processRequestJBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        processRequestJBtn.setText("Process Request");
        processRequestJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processRequestJBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage user - 2.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(assignToMeJBtn)
                        .addGap(77, 77, 77)
                        .addComponent(processRequestJBtn)
                        .addGap(212, 212, 212)))
                .addContainerGap(557, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignToMeJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processRequestJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignToMeJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeJBtnActionPerformed
    int selectedRow = directorWorkRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a request first.");
            return;
        }

        WorkRequest request = (WorkRequest) directorWorkRequestJTable.getValueAt(selectedRow, 5);

        if (!request.getRequestStatus().equals("Sent to Director")) {
            JOptionPane.showMessageDialog(null, "Request cannot be assigned.");
            return;
        }

        request.setRequestReceiver(directorAccount);
        request.setRequestStatus("Pending on Director");

        JOptionPane.showMessageDialog(null, "Assigned to you.");
        populateDirectorTable();

    }//GEN-LAST:event_assignToMeJBtnActionPerformed

    private void processRequestJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processRequestJBtnActionPerformed
        // TODO add your handling code here:
    int row = directorWorkRequestJTable.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Select a request first.");
            return;
        }

        NGOFundRequest fundReq =
                (NGOFundRequest) directorWorkRequestJTable.getValueAt(row, 5);

        if (!directorAccount.equals(fundReq.getRequestReceiver())) {
            JOptionPane.showMessageDialog(null,
                    "Request is not assigned to you!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (fundReq.getRequestStatus().equals("Approved by Director")) {
            JOptionPane.showMessageDialog(null, "Request is already completed.");
            return;
        }
                NGODirectorProcessWRJPanel processPanel =
                new NGODirectorProcessWRJPanel(containerPanel, fundReq);

        containerPanel.add("NGODirectorProcessWRJPanel", processPanel);
        ((CardLayout) containerPanel.getLayout()).next(containerPanel);
    }//GEN-LAST:event_processRequestJBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeJBtn;
    private javax.swing.JTable directorWorkRequestJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processRequestJBtn;
    // End of variables declaration//GEN-END:variables
}

