/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HealthcareAccountant;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceEnterprise;
import Business.Insurance.Insurance;
import Business.CustomerInsurance.CustomerInsurance;
import Business.Network.Network;
import Business.Organization.AccountantOrg;
import Business.Organization.InsuranceAgentOrg;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AccountantBillingRequest;
import Business.WorkQueue.InsuranceWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DecimalFormat;
import java.util.List;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jayan
 */
public class AccountantProcessRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private AccountantOrg organization;
    private AccountantBillingRequest billingRequest;
    private Ecosystem ecosystem;
    private double payableAmount;

    /**
     * Creates new form AccountantProcessRequestJPanel
     */
    public AccountantProcessRequestJPanel(JPanel userProcessContainer, UserAccount account, AccountantBillingRequest request, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.organization = organization;
        this.billingRequest = request;
        this.ecosystem = ecosystem;
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblBillAmount = new javax.swing.JLabel();
        lblInsurancePolicyName = new javax.swing.JLabel();
        lblPayableAmount = new javax.swing.JLabel();
        btnInitiateClaimRequest = new javax.swing.JButton();
        fieldSSN = new javax.swing.JTextField();
        fieldInsurancePolicyName = new javax.swing.JTextField();
        fieldPayableAmount = new javax.swing.JTextField();
        frstNmTxt = new javax.swing.JTextField();
        fieldBillAmount = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldPolicyNumber = new javax.swing.JTextField();
        lblPolicyNumber = new javax.swing.JLabel();
        lblInsuranceClaimAmount = new javax.swing.JLabel();
        fieldInsuranceClaimAmount = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCompleteTransaction = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setText("Process Billing Request Area");

        lblSSN.setBackground(new java.awt.Color(255, 255, 255));
        lblSSN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSSN.setText("SSN");

        lblFirstName.setBackground(new java.awt.Color(255, 255, 255));
        lblFirstName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFirstName.setText("First Name");

        lblLastName.setBackground(new java.awt.Color(255, 255, 255));
        lblLastName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLastName.setText("Last Name");

        lblBillAmount.setBackground(new java.awt.Color(255, 255, 255));
        lblBillAmount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBillAmount.setText("Bill Amount");

        lblInsurancePolicyName.setBackground(new java.awt.Color(255, 255, 255));
        lblInsurancePolicyName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblInsurancePolicyName.setText("Insurance Policy Name");

        lblPayableAmount.setBackground(new java.awt.Color(255, 255, 255));
        lblPayableAmount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPayableAmount.setText("Payable Amount");

        btnInitiateClaimRequest.setBackground(new java.awt.Color(255, 102, 102));
        btnInitiateClaimRequest.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnInitiateClaimRequest.setText("Charge Amount / Initiate Claim Request");
        btnInitiateClaimRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitiateClaimRequestActionPerformed(evt);
            }
        });

        fieldSSN.setEditable(false);

        fieldInsurancePolicyName.setEditable(false);

        fieldPayableAmount.setEditable(false);

        frstNmTxt.setEditable(false);

        fieldBillAmount.setEditable(false);

        fieldLastName.setEditable(false);

        fieldPolicyNumber.setEditable(false);

        lblPolicyNumber.setBackground(new java.awt.Color(255, 255, 255));
        lblPolicyNumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPolicyNumber.setText("Policy Number");

        lblInsuranceClaimAmount.setBackground(new java.awt.Color(255, 255, 255));
        lblInsuranceClaimAmount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblInsuranceClaimAmount.setText("Insurance Claim Amount");

        fieldInsuranceClaimAmount.setEditable(false);

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCompleteTransaction.setBackground(new java.awt.Color(255, 102, 102));
        btnCompleteTransaction.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCompleteTransaction.setText("Complete Patient Transaction");
        btnCompleteTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteTransactionActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Accountant.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnBack)
                        .addGap(104, 104, 104)
                        .addComponent(lblTitle))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(136, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblPolicyNumber)
                                        .addComponent(lblInsurancePolicyName))
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldInsurancePolicyName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldPolicyNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPayableAmount)
                                        .addGap(52, 52, 52)
                                        .addComponent(fieldPayableAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblInsuranceClaimAmount)
                                        .addGap(52, 52, 52)
                                        .addComponent(fieldInsuranceClaimAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(77, 77, 77)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblSSN)
                                        .addComponent(lblFirstName)
                                        .addComponent(lblLastName)
                                        .addComponent(lblBillAmount))
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(frstNmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(fieldSSN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(48, 48, 48)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addComponent(btnInitiateClaimRequest)
                            .addGap(32, 32, 32)
                            .addComponent(btnCompleteTransaction))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPolicyNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldInsurancePolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInsurancePolicyName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSN)
                            .addComponent(fieldSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(frstNmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBillAmount)
                            .addComponent(fieldBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInsuranceClaimAmount)
                            .addComponent(fieldInsuranceClaimAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPayableAmount)
                            .addComponent(fieldPayableAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInitiateClaimRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompleteTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInitiateClaimRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitiateClaimRequestActionPerformed
        String policyNumber = billingRequest.getPatientRecord().getCustomerInsurance().getInsurancePolicyNumber();
        String ssn = billingRequest.getPatientRecord().getSsn();
        String policyName = billingRequest.getPatientRecord().getCustomerInsurance().getInsurance().getPolicyName();
        String insuranceCompany = billingRequest.getPatientRecord().getCustomerInsurance().getInsurance().getInsuranceCompany();
        double claimAmount = Double.parseDouble(fieldInsuranceClaimAmount.getText());
        double billAmount = billingRequest.getTotalBillAmount();
        
        if (("Patient Transaction Completed").equals(billingRequest.getRequestStatus())) {
            JOptionPane.showMessageDialog(null, "Insurance request sent for claim");
            return;
        }
        
        Insurance insurance = new Insurance(policyName, insuranceCompany, claimAmount);
        insurance.setCoverage(billingRequest.getPatientRecord().getCustomerInsurance().getInsurance().getCoverage());
        
        CustomerInsurance customerInsurance = new CustomerInsurance(insurance, policyNumber);
        customerInsurance.setCustomerFirstName(frstNmTxt.getText().trim());
        customerInsurance.setCustomerLastName(fieldLastName.getText().trim());

        InsuranceWorkRequest insuranceWorkRequest = new InsuranceWorkRequest();
        insuranceWorkRequest.setInsuranceProvider(insuranceCompany);
        insuranceWorkRequest.setPolicyNumber(policyNumber);
        insuranceWorkRequest.setPolicyName(policyName);
        insuranceWorkRequest.setPatientSsn(ssn);
        insuranceWorkRequest.setClaimAmount(claimAmount);
        insuranceWorkRequest.setTreatmentBill(billAmount);
        insuranceWorkRequest.setMedicalCenter(enterprise.getName());

        insuranceWorkRequest.setRequestSender(account);
        insuranceWorkRequest.setRequestStatus("Sent");
        insuranceWorkRequest.setInsuredPatient(customerInsurance);

        Organization org = null;
        InsuranceEnterprise matchedInsuranceCompany = null;

        List<Network> networks = ecosystem.getNetworks();
        for (Network network : networks) {
            List<Enterprise> enterprises = network.getEnterpriseDirectory().getEnterpriseList();
            for (Enterprise enterprise : enterprises) {
                if (enterprise.getName().equalsIgnoreCase(billingRequest.getPatientRecord().getCustomerInsurance().getInsurance().getInsuranceCompany())) {
                    matchedInsuranceCompany = (InsuranceEnterprise) enterprise;
                }
            }
        }

        for (Organization organization : matchedInsuranceCompany.getOrgDir().getOrganizations()) {
            if (organization instanceof InsuranceAgentOrg) {
                org = organization;
                break;
            }
        }
        
        if (org != null) {
            org.getWorkQueue().getWorkRequests().add(insuranceWorkRequest);
            account.getWorkQueue().getWorkRequests().add(insuranceWorkRequest);
            billingRequest.setRequestStatus("Patient Transaction Completed");
            billingRequest.getPatientRecord().setIsTreatmentDone(true);
            JOptionPane.showMessageDialog(null, "Money received from patient: $" + String.format("%.2f", payableAmount) + ". Insurance Claim Request Raised Successfully for amount: $" + claimAmount);
            btnInitiateClaimRequest.setEnabled(false);
        }
    }//GEN-LAST:event_btnInitiateClaimRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProcessMedicalBillingsJPanel processMedicalBillingsJPanel = (ProcessMedicalBillingsJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCompleteTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteTransactionActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("EmailBillingInformationToPatientJPanel", new EmailBillingInformationToPatientJPanel(userProcessContainer, billingRequest));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCompleteTransactionActionPerformed
        
    private void populateFields() {
        String policyNumber = billingRequest.getPatientRecord().getCustomerInsurance().getInsurancePolicyNumber();
        DecimalFormat df2 = new DecimalFormat("#.##");
        double coverage = billingRequest.getPatientRecord().getCustomerInsurance().getInsurance().getCoverage();
        double billAmount = billingRequest.getTotalBillAmount();
        String ssn = billingRequest.getPatientRecord().getSsn();
        String policyName = billingRequest.getPatientRecord().getCustomerInsurance().getInsurance().getPolicyName();
        String insuranceCompany = billingRequest.getPatientRecord().getCustomerInsurance().getInsurance().getInsuranceCompany();
        double claimAmount = (coverage * billAmount) / 100;
        payableAmount = billAmount - claimAmount;

        fieldPolicyNumber.setText(policyNumber);
        fieldSSN.setText(ssn);
        frstNmTxt.setText(billingRequest.getPatientRecord().getPatientFirstName());
        fieldLastName.setText(billingRequest.getPatientRecord().getPatientLastName());
        fieldBillAmount.setText(String.valueOf(billAmount));
        fieldInsurancePolicyName.setText(policyName);
        fieldInsuranceClaimAmount.setText(String.valueOf(claimAmount));
        fieldPayableAmount.setText(String.valueOf(df2.format(payableAmount)));

        if (claimAmount > 0) {
            btnInitiateClaimRequest.setEnabled(true);
            btnCompleteTransaction.setEnabled(false);
        } else {
            btnCompleteTransaction.setEnabled(true);
            btnInitiateClaimRequest.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCompleteTransaction;
    private javax.swing.JButton btnInitiateClaimRequest;
    private javax.swing.JTextField fieldBillAmount;
    private javax.swing.JTextField fieldInsuranceClaimAmount;
    private javax.swing.JTextField fieldInsurancePolicyName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldPayableAmount;
    private javax.swing.JTextField fieldPolicyNumber;
    private javax.swing.JTextField fieldSSN;
    private javax.swing.JTextField frstNmTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel lblBillAmount;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblInsuranceClaimAmount;
    private javax.swing.JLabel lblInsurancePolicyName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPayableAmount;
    private javax.swing.JLabel lblPolicyNumber;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
