/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HealthcareAccountant;


import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jayan
 */
public class CreateAppointmentJPanel extends javax.swing.JPanel {
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        txtPatientId11 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblPatientSSN = new javax.swing.JLabel();
        fieldPatientSSN = new javax.swing.JTextField();
        btnFindPatient = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        lblPatientInformation = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        fieldSSN = new javax.swing.JTextField();
        fieldPhoneNumber = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        fieldAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        radioBtnMale = new javax.swing.JRadioButton();
        radioBtnFemale = new javax.swing.JRadioButton();
        lblInsurnaceInformation = new javax.swing.JLabel();
        radioBtnPatientInsuranceYes = new javax.swing.JRadioButton();
        radioBtnPatientInsuranceNo = new javax.swing.JRadioButton();
        lblHaveInsurnacePolicy = new javax.swing.JLabel();
        lblPolicyName = new javax.swing.JLabel();
        lblInsuranceCompany = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        lblReasonForVisit = new javax.swing.JLabel();
        fieldReasonForVisit = new javax.swing.JTextField();
        lblPatientMedicalCondition = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldAddress = new javax.swing.JTextArea();
        lblInsurnacePolicyNo = new javax.swing.JLabel();
        fieldInsurnacePolicyNo = new javax.swing.JTextField();
        btnFindInsurancePolicy = new javax.swing.JButton();
        fieldInsuranceCompany = new javax.swing.JTextField();
        fieldPolicyName = new javax.swing.JTextField();
        fieldDate = new javax.swing.JTextField();
        lblCoveragepercent = new javax.swing.JLabel();
        fieldInsuranceCoverage = new javax.swing.JTextField();
        radioBtnOther = new javax.swing.JRadioButton();
        lblPatientID = new javax.swing.JLabel();
        fieldPatientID = new javax.swing.JTextField();
        btnResetPolicyNum = new javax.swing.JButton();
        lblPatientEmail = new javax.swing.JLabel();
        fieldPatientEmail = new javax.swing.JTextField();
        lblDoctorType = new javax.swing.JLabel();
        jcomboBoxDoctorType = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        jLabel14.setText("Middle Name :");

        setBackground(new java.awt.Color(0, 153, 204));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setText("CREATE APPOINTMENT");

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPatientSSN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPatientSSN.setText("Already registered? Provide SSN: ");

        btnFindPatient.setBackground(new java.awt.Color(255, 102, 102));
        btnFindPatient.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnFindPatient.setText("Find Patient");
        btnFindPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPatientActionPerformed(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDate.setText("Date:");

        lblPatientInformation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPatientInformation.setText("PATIENT INFORMATION");

        lblFirstName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFirstName.setText("First Name :");

        lblAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAddress.setText("Address:");

        lblLastName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLastName.setText("Last Name :");

        lblSSN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSSN.setText("SSN :");

        fieldPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPhoneNumberActionPerformed(evt);
            }
        });

        lblPhoneNumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPhoneNumber.setText("Phone Number:");

        fieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAgeActionPerformed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAge.setText("Age :");

        lblSex.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSex.setText("Sex :");

        buttonGroup2.add(radioBtnMale);
        radioBtnMale.setText("M");
        radioBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMaleActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioBtnFemale);
        radioBtnFemale.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radioBtnFemale.setText("F");
        radioBtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnFemaleActionPerformed(evt);
            }
        });

        lblInsurnaceInformation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblInsurnaceInformation.setText("INSURANCE INFORMATION");

        buttonGroup1.add(radioBtnPatientInsuranceYes);
        radioBtnPatientInsuranceYes.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        radioBtnPatientInsuranceYes.setText("Yes");
        radioBtnPatientInsuranceYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPatientInsuranceYesActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBtnPatientInsuranceNo);
        radioBtnPatientInsuranceNo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        radioBtnPatientInsuranceNo.setText("No");
        radioBtnPatientInsuranceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPatientInsuranceNoActionPerformed(evt);
            }
        });

        lblHaveInsurnacePolicy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblHaveInsurnacePolicy.setText("Is this patient covered by Insurance");

        lblPolicyName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPolicyName.setText("Policy Name :");

        lblInsuranceCompany.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblInsuranceCompany.setText("Insurance Company :");

        btnCreate.setBackground(new java.awt.Color(255, 102, 102));
        btnCreate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblReasonForVisit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblReasonForVisit.setText("Reason for Visit:");

        lblPatientMedicalCondition.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPatientMedicalCondition.setText("PATIENT MEDICAL CONDITION");

        fieldAddress.setColumns(20);
        fieldAddress.setRows(5);
        jScrollPane1.setViewportView(fieldAddress);

        lblInsurnacePolicyNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblInsurnacePolicyNo.setText("Provide Insurance Policy Number:");

        fieldInsurnacePolicyNo.setEnabled(false);

        btnFindInsurancePolicy.setBackground(new java.awt.Color(255, 102, 102));
        btnFindInsurancePolicy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnFindInsurancePolicy.setText("Find Policy");
        btnFindInsurancePolicy.setEnabled(false);
        btnFindInsurancePolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindInsurancePolicyActionPerformed(evt);
            }
        });

        lblCoveragepercent.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCoveragepercent.setText("Patient Insurance Coverage % :");

        buttonGroup2.add(radioBtnOther);
        radioBtnOther.setText("Other");

        lblPatientID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPatientID.setText("Patient ID / Visit ID :");

        btnResetPolicyNum.setBackground(new java.awt.Color(255, 102, 102));
        btnResetPolicyNum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnResetPolicyNum.setText("Reset Policy Number");
        btnResetPolicyNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPolicyNumActionPerformed(evt);
            }
        });

        lblPatientEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPatientEmail.setText("Patient Email:");

        lblDoctorType.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDoctorType.setText("Doctor Type");

        jcomboBoxDoctorType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Physician", "Neurologist", "Pediatrician", "Orthopedic" }));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient details.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(279, 279, 279)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblLastName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(lblSSN)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(fieldSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblSex)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(radioBtnFemale)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(radioBtnMale)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(radioBtnOther))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAge)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(204, 204, 204)
                                            .addComponent(lblPatientInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(291, 291, 291)
                                            .addComponent(lblPatientEmail)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldPatientEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addGap(319, 319, 319)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPhoneNumber)
                                .addComponent(lblFirstName))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnBack)
                                .addGap(249, 249, 249)
                                .addComponent(lblTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPatientSSN)
                                            .addComponent(lblPatientID, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fieldPatientSSN)
                                            .addComponent(fieldPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(fieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnFindPatient)
                                .addGap(40, 40, 40)
                                .addComponent(lblDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(380, 380, 380)
                                .addComponent(lblInsurnaceInformation))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblReasonForVisit)
                                            .addComponent(lblDoctorType))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcomboBoxDoctorType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldReasonForVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblInsuranceCompany)
                                                .addGap(18, 18, 18)
                                                .addComponent(fieldInsuranceCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCoveragepercent)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fieldInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblInsurnacePolicyNo)
                                                .addGap(2, 2, 2)
                                                .addComponent(fieldInsurnacePolicyNo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnFindInsurancePolicy)
                                                .addGap(42, 42, 42))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblPolicyName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPatientMedicalCondition)
                                        .addGap(12, 12, 12)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnResetPolicyNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fieldPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(lblHaveInsurnacePolicy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioBtnPatientInsuranceYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnPatientInsuranceNo)))
                        .addGap(28, 28, 28)))
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPatientSSN)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldPatientSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFindPatient)
                        .addComponent(fieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldPatientEmail)
                        .addComponent(lblPatientEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPatientID)
                        .addComponent(fieldPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAge)
                                    .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSex)
                                .addComponent(radioBtnMale)
                                .addComponent(radioBtnFemale)
                                .addComponent(radioBtnOther))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblPatientInformation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFirstName)
                                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhoneNumber)
                                    .addComponent(lblSSN)
                                    .addComponent(fieldSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblLastName)
                                .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInsurnaceInformation)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHaveInsurnacePolicy)
                            .addComponent(radioBtnPatientInsuranceYes)
                            .addComponent(radioBtnPatientInsuranceNo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInsurnacePolicyNo)
                            .addComponent(fieldInsurnacePolicyNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFindInsurancePolicy)
                            .addComponent(btnResetPolicyNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPolicyName)
                                .addComponent(fieldPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblInsuranceCompany)
                                .addComponent(fieldInsuranceCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCoveragepercent)
                            .addComponent(fieldInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(lblPatientMedicalCondition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcomboBoxDoctorType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDoctorType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldReasonForVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReasonForVisit))
                        .addGap(18, 18, 18)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPhoneNumberActionPerformed

    private void fieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAgeActionPerformed

    private void radioBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnMaleActionPerformed

    private void radioBtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnFemaleActionPerformed

    private void radioBtnPatientInsuranceYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPatientInsuranceYesActionPerformed
        

    }//GEN-LAST:event_radioBtnPatientInsuranceYesActionPerformed

    private void radioBtnPatientInsuranceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPatientInsuranceNoActionPerformed
        
        
    }//GEN-LAST:event_radioBtnPatientInsuranceNoActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnFindPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPatientActionPerformed
        
       
    }//GEN-LAST:event_btnFindPatientActionPerformed

    private void btnFindInsurancePolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindInsurancePolicyActionPerformed
        
    }//GEN-LAST:event_btnFindInsurancePolicyActionPerformed

    private void btnResetPolicyNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPolicyNumActionPerformed
        
    }//GEN-LAST:event_btnResetPolicyNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnFindInsurancePolicy;
    private javax.swing.JButton btnFindPatient;
    private javax.swing.JButton btnResetPolicyNum;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextArea fieldAddress;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldInsuranceCompany;
    private javax.swing.JTextField fieldInsuranceCoverage;
    private javax.swing.JTextField fieldInsurnacePolicyNo;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldPatientEmail;
    private javax.swing.JTextField fieldPatientID;
    private javax.swing.JTextField fieldPatientSSN;
    private javax.swing.JTextField fieldPhoneNumber;
    private javax.swing.JTextField fieldPolicyName;
    private javax.swing.JTextField fieldReasonForVisit;
    private javax.swing.JTextField fieldSSN;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcomboBoxDoctorType;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCoveragepercent;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDoctorType;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHaveInsurnacePolicy;
    private javax.swing.JLabel lblInsuranceCompany;
    private javax.swing.JLabel lblInsurnaceInformation;
    private javax.swing.JLabel lblInsurnacePolicyNo;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPatientEmail;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPatientInformation;
    private javax.swing.JLabel lblPatientMedicalCondition;
    private javax.swing.JLabel lblPatientSSN;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPolicyName;
    private javax.swing.JLabel lblReasonForVisit;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radioBtnFemale;
    private javax.swing.JRadioButton radioBtnMale;
    private javax.swing.JRadioButton radioBtnOther;
    private javax.swing.JRadioButton radioBtnPatientInsuranceNo;
    private javax.swing.JRadioButton radioBtnPatientInsuranceYes;
    private javax.swing.JTextField txtPatientId11;
    // End of variables declaration//GEN-END:variables

}
