/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
*/

package UI.SystemAdmin;
import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.EnterpriseAdmin;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author MALLESH
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Ecosystem system;
    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        usernameJTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        passwordJTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        reenterPasswordJTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        nameJTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateNetworkComboBox();
    
    }
    
        private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseNameJTable.getModel();
        model.setRowCount(0);

        for (Network network : system.getNetworks()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[4];
                    row[0] = enterprise.getName();
                    row[1] = network.getNetworkName();
                    row[2] = ua.getUsername();
                    row[3] = enterprise.getEnterpriseType().getValue();

                    model.addRow(row);
                }
            }
        }

        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        enterpriseNameJTable.setRowSorter(sorter);
    }
        
        private void populateNetworkComboBox() {
        networkJCmboBox.removeAllItems();

        for (Network network : system.getNetworks()) {
            networkJCmboBox.addItem(network);
        }
    }
        
    private void populateEnterpriseComboBox(Network network) {
        enterprisesJCmboBox.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            enterprisesJCmboBox.addItem(enterprise);
        }
    }     

    private boolean isPasswordValid() {
        Pattern p = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[$+_])(?=\\S+$).{6,}$");
        Matcher m = p.matcher(String.valueOf(passwordJTxtField.getPassword()));
        return m.matches();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseNameJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        networkJCmboBox = new javax.swing.JComboBox();
        usernameJLabel = new javax.swing.JLabel();
        usernameJTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enterprisesJCmboBox = new javax.swing.JComboBox();
        submitJBtn = new javax.swing.JButton();
        passwordJLabel = new javax.swing.JLabel();
        nameJTxtField = new javax.swing.JTextField();
        nameJLabel = new javax.swing.JLabel();
        passwordJTxtField = new javax.swing.JPasswordField();
        backJButton = new javax.swing.JButton();
        reenterPasswordJTxtField = new javax.swing.JPasswordField();
        rePasswordJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entuname = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(null);

        enterpriseNameJTable.setBackground(new java.awt.Color(204, 204, 204));
        enterpriseNameJTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        enterpriseNameJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Username", "Enterprise Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseNameJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(26, 62, 671, 88);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Network");
        add(jLabel1);
        jLabel1.setBounds(88, 168, 52, 17);

        networkJCmboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJCmboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJCmboBoxActionPerformed(evt);
            }
        });
        add(networkJCmboBox);
        networkJCmboBox.setBounds(182, 166, 136, 23);

        usernameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usernameJLabel.setText("Username");
        add(usernameJLabel);
        usernameJLabel.setBounds(70, 232, 70, 17);

        usernameJTxtField.setBackground(new java.awt.Color(204, 204, 204));
        add(usernameJTxtField);
        usernameJTxtField.setBounds(182, 228, 136, 25);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Enterprise");
        add(jLabel3);
        jLabel3.setBounds(73, 199, 70, 17);

        enterprisesJCmboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterprisesJCmboBox);
        enterprisesJCmboBox.setBounds(182, 197, 136, 23);

        submitJBtn.setBackground(new java.awt.Color(204, 204, 204));
        submitJBtn.setText("Submit");
        submitJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJBtnActionPerformed(evt);
            }
        });
        add(submitJBtn);
        submitJBtn.setBounds(182, 375, 80, 23);

        passwordJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passwordJLabel.setText("Password");
        add(passwordJLabel);
        passwordJLabel.setBounds(84, 268, 57, 17);

        nameJTxtField.setBackground(new java.awt.Color(204, 204, 204));
        nameJTxtField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(nameJTxtField);
        nameJTxtField.setBounds(182, 341, 136, 28);

        nameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nameJLabel.setText("Name");
        add(nameJLabel);
        nameJLabel.setBounds(93, 347, 50, 17);

        passwordJTxtField.setBackground(new java.awt.Color(204, 204, 204));
        add(passwordJTxtField);
        passwordJTxtField.setBounds(182, 264, 136, 25);

        backJButton.setBackground(new java.awt.Color(204, 204, 204));
        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(10, 11, 90, 23);

        reenterPasswordJTxtField.setBackground(new java.awt.Color(204, 204, 204));
        reenterPasswordJTxtField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(reenterPasswordJTxtField);
        reenterPasswordJTxtField.setBounds(182, 300, 136, 29);

        rePasswordJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rePasswordJLabel.setText("re-enter Password");
        add(rePasswordJLabel);
        rePasswordJLabel.setBounds(30, 306, 109, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Enterprise Admin Management");
        add(jLabel2);
        jLabel2.setBounds(160, 30, 380, 29);

        entuname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entuname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emp2.gif"))); // NOI18N
        add(entuname);
        entuname.setBounds(20, 160, 1060, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void networkJCmboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJCmboBoxActionPerformed
        Network network = (Network) networkJCmboBox.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }

    }//GEN-LAST:event_networkJCmboBoxActionPerformed

    private void submitJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJBtnActionPerformed

        Enterprise enterprise = (Enterprise) enterprisesJCmboBox.getSelectedItem();

        String username = usernameJTxtField.getText().trim();
        String password = String.valueOf(passwordJTxtField.getPassword());
        String rePassword = String.valueOf(reenterPasswordJTxtField.getPassword());
        String name = nameJTxtField.getText().trim();

        // VALIDATIONS ---------------------------------------------------------
        if (username.isEmpty()) {
            usernameJTxtField.setBorder(BorderFactory.createLineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Username cannot be empty");
            return;
        }

        if (password.isEmpty()) {
            passwordJTxtField.setBorder(BorderFactory.createLineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Password cannot be empty");
            return;
        }

        if (!isPasswordValid()) {
            JOptionPane.showMessageDialog(null,
                    "Password must:\n"
                    + "• Be at least 6 char\n"
                    + "• Include 1 number\n"
                    + "• Include 1 lowercase\n"
                    + "• Include 1 uppercase\n"
                    + "• Include only $, +, _ as special chars");
            return;
        }

        if (!password.equals(rePassword)) {
            JOptionPane.showMessageDialog(null, "Passwords do not match!");
            return;
        }

        if (name.isEmpty()) {
            nameJTxtField.setBorder(BorderFactory.createLineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Name cannot be empty");
            return;
        }

        // CHECK IF USERNAME EXISTS
        List<UserAccount> uaList = enterprise.getUserAccountDirectory().getUserAccountList();
        for (UserAccount ua : uaList) {
            if (ua.getUsername().equals(username)) {
                JOptionPane.showMessageDialog(null, "Username already exists!");
                return;
            }
        }

        // CREATION LOGIC ------------------------------------------------------
        Employee emp = enterprise.getEmployeeDirectory().createEmployee(name);
        enterprise.getUserAccountDirectory().createUserAccount(username, password, emp, new EnterpriseAdmin());

        JOptionPane.showMessageDialog(null, "Enterprise Admin Created Successfully!");

        // REFRESH TABLE
        populateTable();

        // RESET FIELDS
        usernameJTxtField.setText("");
        passwordJTxtField.setText("");
        reenterPasswordJTxtField.setText("");
        nameJTxtField.setText("");

        // Restore UI borders
        usernameJTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        passwordJTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        reenterPasswordJTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        nameJTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));

    }//GEN-LAST:event_submitJBtnActionPerformed



    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable enterpriseNameJTable;
    private javax.swing.JComboBox enterprisesJCmboBox;
    private javax.swing.JLabel entuname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTxtField;
    private javax.swing.JComboBox networkJCmboBox;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJTxtField;
    private javax.swing.JLabel rePasswordJLabel;
    private javax.swing.JPasswordField reenterPasswordJTxtField;
    private javax.swing.JButton submitJBtn;
    private javax.swing.JLabel usernameJLabel;
    private javax.swing.JTextField usernameJTxtField;
    // End of variables declaration//GEN-END:variables
}
