/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdmin;


/**
 *
 * @author MALLESH
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {


    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseAdminJPanel() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseNameJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        networkJCmboBox = new javax.swing.JComboBox();
        usernameJLabel = new javax.swing.JLabel();
        usernameJTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enterprisesJCmboBox = new javax.swing.JComboBox();
        submitJBtn = new javax.swing.JButton();
        passwordJLabel = new javax.swing.JLabel();
        nameJTxtField = new javax.swing.JTextField();
        nameJLabel = new javax.swing.JLabel();
        passwordJTxtField = new javax.swing.JPasswordField();
        backJButton = new javax.swing.JButton();
        reenterPasswordJTxtField = new javax.swing.JPasswordField();
        rePasswordJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entuname = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(null);

        enterpriseNameJTable.setBackground(new java.awt.Color(204, 204, 204));
        enterpriseNameJTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        enterpriseNameJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Username", "Enterprise Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseNameJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(26, 62, 671, 88);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Network");
        add(jLabel1);
        jLabel1.setBounds(88, 168, 52, 17);

        networkJCmboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJCmboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJCmboBoxActionPerformed(evt);
            }
        });
        add(networkJCmboBox);
        networkJCmboBox.setBounds(182, 166, 136, 23);

        usernameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usernameJLabel.setText("Username");
        add(usernameJLabel);
        usernameJLabel.setBounds(70, 232, 70, 17);

        usernameJTxtField.setBackground(new java.awt.Color(204, 204, 204));
        add(usernameJTxtField);
        usernameJTxtField.setBounds(182, 228, 136, 25);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Enterprise");
        add(jLabel3);
        jLabel3.setBounds(73, 199, 70, 17);

        enterprisesJCmboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterprisesJCmboBox);
        enterprisesJCmboBox.setBounds(182, 197, 136, 23);

        submitJBtn.setBackground(new java.awt.Color(204, 204, 204));
        submitJBtn.setText("Submit");
        submitJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJBtnActionPerformed(evt);
            }
        });
        add(submitJBtn);
        submitJBtn.setBounds(182, 375, 80, 23);

        passwordJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passwordJLabel.setText("Password");
        add(passwordJLabel);
        passwordJLabel.setBounds(84, 268, 57, 17);

        nameJTxtField.setBackground(new java.awt.Color(204, 204, 204));
        nameJTxtField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(nameJTxtField);
        nameJTxtField.setBounds(182, 341, 136, 28);

        nameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nameJLabel.setText("Name");
        add(nameJLabel);
        nameJLabel.setBounds(93, 347, 50, 17);

        passwordJTxtField.setBackground(new java.awt.Color(204, 204, 204));
        add(passwordJTxtField);
        passwordJTxtField.setBounds(182, 264, 136, 25);

        backJButton.setBackground(new java.awt.Color(204, 204, 204));
        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(10, 11, 90, 23);

        reenterPasswordJTxtField.setBackground(new java.awt.Color(204, 204, 204));
        reenterPasswordJTxtField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(reenterPasswordJTxtField);
        reenterPasswordJTxtField.setBounds(182, 300, 136, 29);

        rePasswordJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rePasswordJLabel.setText("re-enter Password");
        add(rePasswordJLabel);
        rePasswordJLabel.setBounds(30, 306, 109, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Enterprise Admin Management");
        add(jLabel2);
        jLabel2.setBounds(160, 30, 380, 29);

        entuname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entuname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emp2.gif"))); // NOI18N
        add(entuname);
        entuname.setBounds(20, 160, 1060, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void networkJCmboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJCmboBoxActionPerformed


    }//GEN-LAST:event_networkJCmboBoxActionPerformed

    private void submitJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJBtnActionPerformed


    }//GEN-LAST:event_submitJBtnActionPerformed



    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable enterpriseNameJTable;
    private javax.swing.JComboBox enterprisesJCmboBox;
    private javax.swing.JLabel entuname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTxtField;
    private javax.swing.JComboBox networkJCmboBox;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJTxtField;
    private javax.swing.JLabel rePasswordJLabel;
    private javax.swing.JPasswordField reenterPasswordJTxtField;
    private javax.swing.JButton submitJBtn;
    private javax.swing.JLabel usernameJLabel;
    private javax.swing.JTextField usernameJTxtField;
    // End of variables declaration//GEN-END:variables
}
